### ISSUE TITLE
Use with objectbox-android (Java/Kotlin): Duplicate class error

### ISSUE THREAD

**Issue by lzhAndroid** [objectbox/objectbox-dart#103]
when android&flutter all use objectbox,the library merge error.

Duplicate class io.objectbox.android.ObjectBoxLiveData found in modules jetified-objectbox-android-2.5.1-runtime.jar (io.objectbox:objectbox-android:2.5.1) and jetified-objectbox-android-objectbrowser-2.5.1-runtime.jar (io.objectbox:objectbox-android-objectbrowser:2.5.1)

**Comment by vaind** [comment]
So you're using objectbox for android (with java/kotlin) as well as objectbox-dart in the same project? Haven't tried that but I understand that it might be a problem. Maybe it's just that one uses the library with the objectbrowser and the other doesn't and if you could configure it to use the same lib it would work, but that's just a guess... 
@greenrobot-team @greenrobot any ideas?

**Comment by Buggaboo** [comment]
@lzhAndroid I assume you can't use both. I suggest you change your gradle to use the objectbrowser for debug builds, and the other one for production.

**Comment by greenrobot-team** [comment]
@vaind Your assumption is correct. No two libraries in the dependency graph can contribute the same class.

However, if you change dependencies as @Buggaboo suggested it'll break for anyone not using `objectbox-android-objectbrowser`.

I looked at the example but am a little bit at a loss here where exactly the `objectbox-android` dependency is pulled in.

@Buggaboo Typically in Gradle in the consuming project you could exclude any conflicting dependencies:
```groovy
dependencies {
    // Don't pull in from Flutter project.
    project(':wherever:flutter:project:is') {
        exclude group: 'io.objectbox', module: 'objectbox-android'
    }
    // Use these instead:
    debugImplementation "io.objectbox:objectbox-android-objectbrowser:$versions.objectboxVersion"
    releaseImplementation "io.objectbox:objectbox-android:$versions.objectboxVersion"
}
```
Does that not work in your case (again I'm unfamiliar with how the project setup looks like here)?

**Comment by vaind** [comment]
This might be a similar request as the iOS-related #107

**Comment by vaind** [comment]
There has been no follow-up from the OP whether the provided solution fixed the issue so I'm closing this. Feel free to follow up in case this is still an issue.
