### ISSUE TITLE
How to implement observers to return changed objects?

### ISSUE THREAD

**Issue by Buggaboo** [objectbox/objectbox-dart#104]
I got the [observer callbacks in C](https://github.com/objectbox/objectbox-c/blob/master/include/objectbox.h#L1096-L1137) to work on dart a while ago #88 ,
now I want to return the exact objects that have changed with streams, like on java (android).

@vaind @greenrobot ?

**Comment by vaind** [comment]
Core observers don't provide information about the changed data, only what entities (types) have changed. The closest thing to getting data changes is subscribing to queries. I suppose now with query streams available, this issue can be closed.  Feel free to reopen/follow up.
