### ISSUE TITLE
Unable to use objeсеbox both flutter and native side

### ISSUE THREAD

**Issue by softkot** [objectbox/objectbox-dart#107]
Using objectbox on dart side and eventualy going to use in on native side as well. the first step from docs https://swift.objectbox.io/install  saying just add the 

`pod 'ObjectBox' to the Podfile`

And thats instantly leads to compile error saying 

`[!] The 'Pods-Runner' target has frameworks with conflicting names: objectbox.framework.`

How to solve that conflict ?

**Comment by vaind** [comment]
Could you please describe what you're trying to do in more details (maybe including the "why")?

Are you trying to use the same database (file) from swift code and from dart code?

**Comment by softkot** [comment]
WHY: My target was to use object box on flutter (separate database file) and in swift. Both databases are independend and accessed only from the side used for. One i add a flutter plugin i was able to start use object box in dart, after a while i start to code in swidt and the firts step is to include apropriate pod file as described on the link mentioned in the above descrition. That case a compile time conflict.

**Comment by vaind** [comment]
This may have actually been fixed as a side-effect of b6dd0b8a2ac52ee0186be6843eae878242dbdb0f

Feel free to reopen if this is still bothering you.
