### ISSUE TITLE
Invalid Plugin Specification (flutter v1.20+)

### ISSUE THREAD

**Issue by rmtmckenzie** [objectbox/objectbox-dart#112]
When trying to build my app on `Flutter (Channel master, 1.21.0-6.0.pre.42)`, build fails with this error:
"""dart
Invalid plugin specification objectbox.
Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file.
"""

I'm assuming due to the missing specification for android & iOS plugin files.

**Comment by vaind** [comment]
Looks like a new requirement for the upcoming flutter version... A pull
request would be very welcome if you've stumbled upon a solution in the
meantime.

I guess we'll have to address this for the future version support.

**Comment by rmtmckenzie** [comment]
Yeah I'm just working it now tbh, I have android working and just testing out iOS

**Comment by rmtmckenzie** [comment]
Well I gave it a start, but it's crashing on run on iOS (not finding the objectbox symbols I'm thinking). 

I've run out of time to work on it, but here's what I had started on:

https://github.com/rmtmckenzie/objectbox-dart/tree/updated-pubspec-platforms

I'll do a PR if I can get it to work properly.

**Comment by vaind** [comment]
Also WRT to other changes in your branch (updated-pubspec-platforms), those look on a first look but we'll have to wait until the flutter FFI plugin handling is sorted before merging.

**Comment by vaind** [comment]
So... extracting flutter libs to a separate package works for iOS

but breaks Android now... I'll have to see about that:
`E/flutter ( 6747): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libobjectbox-jni.so" not found)`

**Comment by rmtmckenzie** [comment]
I found a way to get this to _almost_ work without having to bother with that. Unfortunately almost isn't the same as just working 😞 . But what I did was set the `module_name` in the podspec to `objectboxdart`. Unfortunately this breaks the flutter build, but actually only in once place - the GeneratedPluginRegistrant.m file. For now I'm probably going to just live with that and modify it by hand after each pub get/update.

What I have done is opened a bug against flutter to have them look into this, as I don't think you'll be the only native library that has collisions with the relevant flutter packages. It's here: https://github.com/flutter/flutter/issues/63240, and what it proposes is a keyword in the plugin's pubspec.yaml which would change the module that the package is symlinked etc to, or at least changes the name of the framework. I could do a PR against flutter for just the module part of it pretty easy, but I'm not 100% sure whether they'd be happy about leaving the name in the search path the same as it is now or whether they'd want to have that set from the moduleName key as well... and in that case I'm not as confident about figuring out how the flutter tool does that in the rather limited amount of time I have to work on this.

Anyways, not immediately helpful but hopefully that's going in the right direction at least...

**Comment by vaind** [comment]
Went with a separate `objectbox_flutter_libs` package flutter users have to depend on in addition to `objectbox` when used in flutter. Dart-only user still only depend on `objectbox`.

Followup to further improve this (if/when possible): #114

**Comment by vaind** [comment]
Should be resolved with the upcoming v0.7.0 so closing. Feel free to follow up in case of further issues.
