### ISSUE TITLE
Is it mature enough to use it in production

### ISSUE THREAD

**Issue by dgandhi17** [objectbox/objectbox-dart#122]
What is the plan for 1.0 stable release I already have used objectbox for Android app and wanted to use for flutter but not sure about it's future plan or roadmap. I guess this library should get more focus as flutter is making fast progress as cross platform and there is less option for mobile databases

**Comment by Buggaboo** [comment]
How do you want to use it?

**Comment by vaind** [comment]
There's no fixed date for 1.0 yet as there are still features missing we usually consider for 1.0 for any language binding. Also, there certainly are going to be breaking changes until 1.0. And of course, the dart version isn't as battle-tested as ObjectBox for Android. Having said that, I suggest you give the dart version a try and see if the current feature set meets your needs.

**Comment by vaind** [comment]
Milestone you can watch (some issues may still be added of course): https://github.com/objectbox/objectbox-dart/milestone/5
