### ISSUE TITLE
Support query with no condition

### ISSUE THREAD

**Issue by greenrobot-team** [objectbox/objectbox-dart#125]
Currently building a query requires specifying at least one condition. E.g. to use the upcoming query observer with an all objects query, this results in strange code like

```dart
final dummyCondition = dateProp.greaterThan(0);
_query = _box.query(dummyCondition)
```

Support building a query with no conditions (AFAIK at least OBX for Java allows this as well).

**Comment by Buggaboo** [comment]
Maybe something like:

```dart

// ctor
Box.emptyQuery() { /* return an empty query, skip the queryBuilder */ }
```
