### ISSUE TITLE
Readme/example improvements

### ISSUE THREAD

**Issue by vaind** [objectbox/objectbox-dart#135]
Follow up from: #130 

We should improve README.md as shown on GitHub and pub.dev and the [example tab on pub.dev](https://pub.dev/packages/objectbox/example).

Maybe take a clue from the most liked packages on pub.dev
* https://pub.dev/packages/provider/example 
* https://pub.dev/packages/shared_preferences
* https://pub.dev/packages/get

**Comment by JostSchenck** [comment]
I'll post this here: For a newcomer to ObjectBox at least, the README.md is very confusing - the division into "Flutter only steps" and "Dart standalone programs" gives the impression, that for flutter only that's all I have to do. However, at least for Flutter Windows applications, I had to get the lib/objectbox.dll and place it in the project directory as well.

**Comment by vaind** [comment]
Thanks for the feedback @JostSchenck. The readme doesn't really consider desktop Flutter apps yet, back when we last tried it those were still kinda work-in-progress, especially with regards to including native libraries. Ideally, you wouldn't have to install anything besides adding the pubspec dependencies, let's see what the current state is... I'll check again and will probably have to update the example as well.
