### ISSUE TITLE
Please add Sync functionality

### ISSUE THREAD

**Issue by RTrackerDev** [objectbox/objectbox-dart#137]

**Comment by vaind** [comment]
This will come aligned with other languages. There's a recent PR draft here: #136

**Comment by RTrackerDev** [comment]
@vaind 
When is this feature planned to be released?

**Comment by vaind** [comment]
> When is this feature planned to be released?

You can sign up at https://objectbox.io/sync/ to get updates about early access.

**Comment by RTrackerDev** [comment]
> > Когда планируется выпустить эту функцию?
> 
> Вы можете зарегистрироваться на [https://objectbox.io/sync/,](https://objectbox.io/sync/) чтобы получать обновления о раннем доступе.

I already))

**Comment by vaind** [comment]
SyncClient has been merged and will be part of the next release (without listeners so far, see #140). For now, please follow up on availability through private channels, starting at  https://objectbox.io/sync/
