### ISSUE TITLE
SyncClient listeners

### ISSUE THREAD

**Issue by vaind** [objectbox/objectbox-dart#140]
#136 brings Sync but without listeners for events. We should add those as well for completeness. 

How would that work? Take a cue from `observable.dart`?

**Comment by Buggaboo** [comment]
I couldn't find [objectbox.h 0.11](https://github.com/objectbox/objectbox-c/blob/main/include/objectbox.h) (yet).

**Comment by vaind** [comment]
the C API's haven't been released yet but they look very similar to `obx_observe()`, i.e. you give the C-API a callback and the C will execute it (or not) at some point in the future

**Comment by vaind** [comment]
Implemented by #145
