### ISSUE TITLE
Flutter plugin deprecated API (ObjectBoxFlutterPlugin.java)

### ISSUE THREAD

**Issue by RTrackerDev** [objectbox/objectbox-dart#147]
![Screenshot 2020-11-16 at 11 06 47](https://user-images.githubusercontent.com/71831255/99234952-e3fab680-27fd-11eb-89e0-cef389ab38f1.png)

**Comment by vaind** [comment]
Seems common for plugins using native code, we'll have a look. Not a `bug` though (it even says "Note:"),  so removing the label

**Comment by RTrackerDev** [comment]
> Кажется обычным для плагинов, использующих собственный код, мы посмотрим. Ни `bug`разу (там даже написано "Примечание:"), поэтому удаление ярлыка

I think there is only a need to delete `public static void registerWith (Registrar registrar) {
    final MethodChannel channel = new MethodChannel (registr.messenger (), "objectbox");
    channel.setMethodCallHandler (new ObjectBoxFlutterPlugin ());
  } `

**Comment by RTrackerDev** [comment]
Also `onAttachedToEngine` should be:
```
@Override
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) {
    channel = new MethodChannel(flutterPluginBinding.getBinaryMessenger(), "objectbox");
    channel.setMethodCallHandler(this);
  }
```
