### ISSUE TITLE
Read and write chunks of memory for CString

### ISSUE THREAD

**Issue by nalenz-objectbox** [objectbox/objectbox-dart#17]
Currently, [writing strings to](https://github.com/objectbox/objectbox-dart/blob/master/lib/src/ffi/cstring.dart#L13) and [reading strings from](https://github.com/objectbox/objectbox-dart/blob/master/lib/src/ffi/cstring.dart#L26) memory is done character by character. Try to find a more efficient method to do that.

Is mostly related to CString (#7), but also memory chunks in general.

**Comment by vaind** [comment]
[Dart FFI homepage](https://dart.dev/guides/libraries/c-interop) links the following example:

Even though it still iterates, it looks less cumbersome than the current solution so maybe we could switch to that if there's no more efficient solution (consider opening an issue on dart github).

**Comment by Buggaboo** [comment]
I'm on it

**Comment by vaind** [comment]
Thanks @Buggaboo for tackling this :1st_place_medal:
