### ISSUE TITLE
Automatically generate IDs and UIDs for entities and properties

### ISSUE THREAD

**Issue by nalenz-objectbox** [objectbox/objectbox-dart#18]
- when writing an entity class, it should be enough to specify the respective annotation without any parameters, i.e. `@Entity() class MyEntity { ... }` should suffice
- all instance variables of the entity class shall be incorporated into the final model and only those with special properties (e.g. `@Id()`) need to be annotated
- all IDs and UIDs need to be generated by `objectbox_model_generator`, together with [these rules](https://docs.objectbox.io/advanced/data-model-updates) on how to resolve changes and conflicts
- in contrast to the current situation, this means that the existing generated file (specifically the `_MyEntity_OBXModel` object) needs to be parsed beforehand in order to detect changes

**Comment by nalenz-objectbox** [comment]
The branch `18-automatic-id-generation` now contains the following changes:

- a file called `objectbox-models.json` is generated with a structure similar to ObjectBox Java
  - only merging entity properties is supported right now, indexes and relations are still completely missing
  - the overall file structure of the new generator is heavily influenced by the Go source you provided the link to
- unannotated fields in an `@Entity()` class now behave just like those annotated with `@Property()`

**Comment by vaind** [comment]
Uff, it's huge already. Please create a pull request (`18-...` to `dev`) so that I can review properly and restrain yourself from adding more stuff (if you planned to do so) unless necessary for this issue - it's going to be hard to review as it is now. Thanks

**Comment by Buggaboo** [comment]
At the risk of increasing the lines of code here, are there plans to support other types other than `String` and `int`? Currently my query tests are failing because things like `bool` and `double` are not supported.

**Comment by vaind** [comment]
> At the risk of increasing the lines of code here, are there plans to support other types other than `String` and `int`? Currently my [query tests](https://github.com/Buggaboo/objectbox-dart/tree/query) are failing because things like `bool` and `double` are not supported.

It's not really related to the original goal of this ticket and should rather be covered by #11 - so that we can merge this PR ASAP.
