### ISSUE TITLE
Support `DateTime` fields in an Entity

### ISSUE THREAD

**Issue by vaind** [objectbox/objectbox-dart#184]
Use `PropertyType.date` with `DateTime` fields automatically

**Comment by hs2361** [comment]
I'm new to the codebase, and I would like to work on this issue. Is this the file in which changes are to be made? https://github.com/objectbox/objectbox-dart/blob/cdf840171d761c866f0a268651f1830032bd67ba/generator/lib/src/entity_resolver.dart

**Comment by vaind** [comment]
Yes, that's a start - the `entity_resolver` needs to recognize the type and set the proper objectbox property data type.
To test your changes, you'd also add such a property to `/objectbox/test/entity.dart` and run `pub run build_runner build` and see the generated `objectbox/test/objectbox.g.dart`.

**Comment by vaind** [comment]
implemented by 1e1dc475157f0b180072f7335a3ae89b3cfc5d7c
