### ISSUE TITLE
Name types using UpperCamelCase on generated files

### ISSUE THREAD

**Issue by Katekko** [objectbox/objectbox-dart#186]
Morning, I'm new on ObjectBox and I'm trying to migrate first my personal project to see if I will can use on production.

I'm getting warning (guess because my lint, but its a common lint for dart, not a custom) because the file generated is creating the class with underscore. There is any solution to fix this warning? Maybe change the pattern used for create these files... Idk just guessing

![Screenshot from 2021-02-03 11-34-39](https://user-images.githubusercontent.com/13632735/106761957-1bfee200-6614-11eb-9075-4df5a5a7dcad.png)

**Comment by vaind** [comment]
Yeah, I've had a TODO about this in the back of my mind, thanks for creating the issue :)

The "underscore" there is something we do in other ObjectBox language bindings so it naturally went in here as well.
I'm not sure yet how to resolve, wouldn't like to add a ObjectBox specific prefix/suffix. Any ideas?

Of we can't think of something, we'll at least add a `ignore_for_file` directive to the generated code so the analyzer won't bother users.

**Comment by Katekko** [comment]
I saw the ignore for file, but now the problem is other: 
![image](https://user-images.githubusercontent.com/13632735/111821320-430e2c00-88c1-11eb-8650-3bbab39d2e46.png)

Adding const will fix the warning

**Comment by vaind** [comment]
> Adding const will fix the warning

Fixed in 27bbb12d6ee58fc5be01880ad23f1b3b2046d2aa
