### ISSUE TITLE
Asignable ID

### ISSUE THREAD

**Issue by juanlabrador** [objectbox/objectbox-dart#188]
Hi! Thanks for this job! Do we have for asignable ID like java - kotlin version? 

@Id(assignable = true)

Thanks.

I try to set id = 1, but I have this error

ObjectBoxException: object put failed: 10002 ID is higher or equal to internal ID sequence: 1 (vs. 1). Use ID 0 (zero) to insert new entities.

**Comment by greenrobot-team** [comment]
Just noting a workaround: add another property and use the recently added `@Index()` or `@Unique()` on it.
