### ISSUE TITLE
Something go wrong. Help 

### ISSUE THREAD

**Issue by Hopheylalal** [objectbox/objectbox-dart#191]
save()async{
    final path = Directory.current.path + '/my.db';
    Directory appDocDir = await getApplicationDocumentsDirectory();
    final db = ObjectDB(appDocDir.path);
    db.open();
// insert document into database
    db.insert({'name': 'qq'});

    result = await db.find({'name.first': 'qq'});
    await db.close();
  }

_____ERROR_______

Restarted application in 8 168ms.
F/libc    (12929): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x80000024 in tid 12957 (1.ui), pid 12929 (ple.flutter_app)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86_arm/generic_x86_arm:11/RSR1.201013.001/6903271:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2021-02-11 09:02:58+0000
pid: 12929, tid: 12957, name: 1.ui  >>> com.example.flutter_app <<<
uid: 10154
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x80000024
    eax 80000000  ebx c12d9420  ecx 00000002  edx 000009ea
    edi be710090  esi 00000003
    ebp c17bc278  esp c17bc210  eip c11c612f
backtrace:
      #00 pc 019c612f  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #01 pc 019c7bb2  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #02 pc 019c70df  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #03 pc 019c6c77  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #04 pc 019c6199  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #05 pc 019c7bb2  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #06 pc 019c502a  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #07 pc 019c3e14  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #08 pc 017f9c7c  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #09 pc 0199395d  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #10 pc 01993718  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #11 pc 019a3d51  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #12 pc 018828d8  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #13 pc 01883ba2  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #14 pc 01884b44  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #15 pc 018845ef  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #16 pc 017aaf5a  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #17 pc 01882d01  /data/app/~~mtsuQtmD3-MDmKBRqz_Lxg==/com.example.flutter_app-k2n3TG_WgSutg7NtO4uF2w==/lib/x86/libflutter.so (BuildId: aaf57673e431d778c3574f8310d08eae434fb178)
      #18 pc 000012ab  <anonymous:be980000>
Lost connection to device.

**Comment by vaind** [comment]
Looks like a different project: https://pub.dev/packages/objectdb
