### ISSUE TITLE
Store images, files as Blob ?

### ISSUE THREAD

**Issue by Dimyvm** [objectbox/objectbox-dart#199]
I am new with ObjectBox.

is there any way to save images, files in an ObjectBox as Blob?
if so what is the best way to achieve this?
If not, is this something that will be added in the future?

Kind regards,
Dimi

**Comment by vaind** [comment]
While it is not the most efficient way to do so (that would be directly on disk I guess), you can store images (and any other binary data) as any of the following three supported field types:

* `List<int>` annotated with `@Property(type: PropertyType.byteVector)`
* `Int8List` from package `'dart:typed_data'`
* `Uint8List` from package `'dart:typed_data'`

**Comment by vaind** [comment]
Additionally, if you want to go this route, then depending on your data model, it may be a good idea to have a separate entity (using `ToOne` relation) just for the image data, so you don't have to load images when you don't need them.

E.g. if consider the following model:

```dart
@Entity
class Book {
   int id;
   
  final cover = ToOne<BookCover>();

  ... // other book information
}

@Entity
class BookCover {
  int id;

  @Property(type: PropertyType.byteVector)
  List<int> image;
}
```

**Comment by vaind** [comment]
@Dimyvm I've noticed the upvote, please close the issue if it answered your question or feel free to follow up.
