### ISSUE TITLE
Upgrade FFI Version to ^1.0.0

### ISSUE THREAD

**Issue by dkobia** [objectbox/objectbox-dart#201]
Any chance we can upgrade the ffi utilities? The latest version of `shared_preferences` depends on `ffi ^1.0.0` released on Feb 11, 2021 for null safety. Objectbox is on `ffi ^0.1.3`.

```
Because no versions of objectbox match >0.12.1 <0.13.0 and objectbox 0.12.1 depends on ffi ^0.1.3, objectbox ^0.12.1 requires ffi ^0.1.3.
And because path_provider_windows >=0.1.0-nullsafety.3 depends on ffi ^1.0.0, objectbox ^0.12.1 is incompatible with path_provider_windows >=0.1.0-nullsafety.3.
And because shared_preferences >=2.0.0 depends on shared_preferences_windows ^2.0.0 which depends on path_provider_windows ^2.0.0, objectbox ^0.12.1 is incompatible with shared_preferences >=2.0.0.
So, because choreboss depends on both shared_preferences ^2.0.3 and objectbox ^0.12.1, version solving failed.
pub get failed (1; So, because choreboss depends on both shared_preferences ^2.0.3 and objectbox ^0.12.1, version solving failed.)
```

**Comment by vaind** [comment]
This is a work in progress and should be available soon(-ish)

Some details why it's not out yet: package FFI 1.0 requires SDK 2.12, so in order to get it in ObjectBox, we need to also increase the SDK constraint to 2.12 as well, which in turn enables null-safety, which was blocked by dependencies (flatbuffers).

**Comment by vaind** [comment]
There's a 0.13.0-nullsafety.0 prerelease now, with this change. If it's an option for you (e.g. you don't need this in production), you can try that version.
