### ISSUE TITLE
Close Query on cancel subscription

### ISSUE THREAD

**Issue by galunecandrey** [objectbox/objectbox-dart#210]
Can you please tell me if I need to close the `query` when I unsubscribed from the stream? Or does it happen automatically?

**Comment by vaind** [comment]
Needs to be closed manually (as we're currently slowing the use outside the
stream)

**Comment by vaind** [comment]
btw the original answer was auto-corrected by my email client: there shuld have been "allowing the use" not "slowing the use"...
