### ISSUE TITLE
Feature request: Queries should be case sensitive

### ISSUE THREAD

**Issue by lamp-town-guy** [objectbox/objectbox-dart#212]
Querying strings should be case sensitive by default. It is a default in all SQL databases. This is very unexpected behavior. Only problem is backwards incompatibility of this change. But since this is a beta release it should not matter much.

Workaround  is writing all queries with `caseSensitive: true`. This is not only unnecessary but also dangerous. For a developer not familiar with querying objectbox it is like a nitroglycerin in a backpack. Just a matter of time before it blows up. I discovered it by accident and I was immediately horrified by it. I don’t think this is a good default behaviour even if it’s documented.

**Comment by vaind** [comment]
Thanks for the valuable input, I'll take the discussion to the core team. To add a little more context: the other side of the coin is alignment between various language bindings of the database (e.g. Java, Swift, Go, ...) and those are well established (not a pre-release like objectbox-dart). 

A first idea: as an alternative to setting the value on each condition, maybe we could have the default (be it true or false) as a global setting you configure on the store/box/field and all subsequently created query conditions would respect that default, unless overridden :thinking:

**Comment by vaind** [comment]
Actually, looks like it was the plan to change the default to case-sensitive for other language bindings (in their next major version). In that case there isn't much keeping us from going with case-sensitive default in dart, before 1.0.

Thanks again for bringing this up.

**Comment by vaind** [comment]
Changed by 0.13.1-dev.0 - should become 0.13.1 tomorrow but you can already try the pre-release version

**Comment by vaind** [comment]
so it's out in 0.14.0, with the default already changed to case-sensitive
