### ISSUE TITLE
Example link is broken in documentation front page

### ISSUE THREAD

**Issue by ChristianKleineidam** [objectbox/objectbox-dart#218]
On https://github.com/objectbox/objectbox-dart/tree/main/objectbox there's currently a link to https://github.com/objectbox/objectbox-dart/blob/main/objectbox/objectbox/example/README.md that resolves with a 404 error. It likely should be https://github.com/objectbox/objectbox-dart/blob/main/objectbox/example/README.md instead.

**Comment by vaind** [comment]
fixed by #222
