### ISSUE TITLE
Placeholder advanced features dart 2.13 + article mention

### ISSUE THREAD

**Issue by Buggaboo** [objectbox/objectbox-dart#225]
I was reading the [release notes for dart 2.12](https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87), and I noticed objectbox got an honorable mention, wrt ffi usage! Good job people!

From the article, we can expect better support for these in the near future:
* static metaprogramming for code generation (maybe we can simplify code generation)
* Type alias (finally)

**Comment by vaind** [comment]
Thanks and you were also part of the effort, so thanks to you too. :+1:

**Comment by vaind** [comment]
BTW I find [Dart SDK changelog on the main branch](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md) a good source of upcoming changes/features. e.g. it already lists 2.13 and 2.14 (WIP)

**Comment by greenrobot-team** [comment]
Closing as this has no concrete tasks. Also had a bunch of improvements thanks to new ffigen versions already.
