### ISSUE TITLE
0.15.0 gives permanent exception "Given transaction callback always fails."

### ISSUE THREAD

**Issue by softkot** [objectbox/objectbox-dart#241]
Just replace dependency on 0.15.0 and the previous working code with query?.findFirst() start throwing me the exception  "Given transaction callback always fails."

**Comment by vaind** [comment]
Also, it's usually better to follow the new issue template - another important question there is whether the application you're using has null-safety enabled

**Comment by vaind** [comment]
OK, so this was caused by the new check to prevent async functions in a transaction. Turns out if users's package doesn't use null-safety, then Null result is indistinguishable from a Future result when checking for function signature.
