### ISSUE TITLE
Should the model be in the lib folder can I change it? how?

### ISSUE THREAD

**Issue by richard457** [objectbox/objectbox-dart#245]

**Comment by vaind** [comment]
You can store the model in any `lib` subdirectory AFAIK. What is it that you're trying to achieve?

**Comment by richard457** [comment]
According to the app structure, you might need to save models in for example packages/models @vaind

**Comment by vaind** [comment]
Are those separate dart packages or the same package and subdirectories in the lib dir? Any chance you can provide a minimal example (app/lib repo)? Maybe what you're trying to do is already supported/doable and if not, a reproducible example would help get us there.

**Comment by vaind** [comment]
Because there was no followup info I assume it's resolved by https://github.com/objectbox/objectbox-dart/pull/341
