### ISSUE TITLE
I/flutter ( 8179): Invalid argument(s): object put failed: 10002 ID is higher or equal to internal ID sequence: 8 (vs. 1). Use ID 0 (zero) to insert new entities.

### ISSUE THREAD

**Issue by ranomoh** [objectbox/objectbox-dart#250]
when we put(add) new objects from remote db, it failed if thier ids are bigger numbers and the older objects with smaller ids was deleted
say we have deleted documents with ids from 1to7 in the device(mobile in my case), if we try to put documents from remote(server) database with ids 8, 9, 10... we get error:
I/flutter ( 8179): Invalid argument(s): object put failed: 10002 ID is higher or equal to internal ID sequence: 8 (vs. 1). Use ID 0 (zero) to insert new entities.

### Basic info:
- ObjectBox version: [0.15.0]
- Flutter/Dart SDK: [2.0.0, or the output of `dart --2.12.2` or `flutter --2.0.4 `]
- Null-safety enabled: [yes]
- Reproducibility: [e.g. occurred once only | occasionally without visible pattern | always]
- OS: [ Windows 10 ]
- Device/Emulator: [NEXUS 6P API 28]

### Logs, stack traces
I/flutter ( 8179): Invalid argument(s): object put failed: 10002 ID is higher or equal to internal ID sequence: 8 (vs. 1). Use ID 0 (zero) to insert new entities.

**Comment by vaind** [comment]
Have you considered https://docs.objectbox.io/advanced/object-ids#self-assigned-object-ids ?

**Comment by ranomoh** [comment]
hello vaind,
as they mentioned in the documentation:
**Warning: self-assigned IDs break automatic state detection (new vs. persisted entity based on the ID). Therefore, you should put entities with self-assigned IDs immediately and may have to attach the box manually, especially when working with relations.**
i searched in google, and I found that some ppl have issues when they try to assign ids by their self (the relationships not working).
could you show me how to add: @Id(assignable = true)in dart file, coz i get: Undefined name 'assignable'.

**Comment by vaind** [comment]
in Dart, the syntax is `@Id(assignable: true)`

Yes, in case you use custom IDs you have to take greater care with relations, as with any other DB.

**Comment by AGenius** [comment]
Personally, where I have data from the server that has an ID I will need I just have an additional field called realID and I am letting objectbox (I used ActiveAndroid in the same way in the old version of my app that I am re-writing)

**Comment by vaind** [comment]
From the lack of a followup it looks like the question was answered.
