### ISSUE TITLE
Help me understand codebase. (Lib generation) and usage in development and in production when package is published at https://pub.dev/

### ISSUE THREAD

**Issue by richard457** [objectbox/objectbox-dart#253]
I am trying to understand the codebase, however, there is something I do not understand at least for now,
```dart
ObjectBoxC? _tryObjectBoxLibFile() {
  _lib = null;
  var libName = 'objectbox';
  if (Platform.isWindows) {
    libName += '.dll';
    try {
      _lib = DynamicLibrary.open(libName);
    } on ArgumentError {
      libName = 'lib/' + libName;
    }
  } else if (Platform.isMacOS) {
    libName = 'lib' + libName + '.dylib';
    try {
      _lib = DynamicLibrary.open(libName);
    } on ArgumentError {
      libName = '/usr/local/lib/' + libName;
    }
  } else if (Platform.isAndroid) {
    libName = 'lib' + libName + '-jni.so';
  } else if (Platform.isLinux) {
    libName = 'lib' + libName + '.so';
  } else {
    return null;
  }
  _lib ??= DynamicLibrary.open(libName);
  return ObjectBoxC(_lib!);
}
```
When I try to understand this looks like we can load lib files from the lib folder, however, I do not see this lib folder, I also try to check the installed 
```yaml
objectbox: ^1.0.0
  objectbox_flutter_libs: any
```
to see if the folder is included within the installation but not, please can you guide me on how stuff is done here?

--------------------
edit by @vaind: codeblocks

**Comment by vaind** [comment]
`objectbox_flutter_libs` is a package that, depending on your platform, gets the native dynamic library (`libobjectbox.so`, `libobjectbox.dylib` or `objectbox.dll`). The code above loads it (so it can access native symbols from objectbox core. Additionaly, that `lib/` folder you see for Windows and the other path for macOS, are there just for convenience for plain Dart users ("Dart native").

**Comment by vaind** [comment]
Any follow-up here? Or can we close the issue/question.

**Comment by richard457** [comment]
I understand now, now would like to see how I can get my contribution to this if you can guide me anyhow please, also would like to know the web support progress, I will have a free time sometimes in weekends please let me know the baby steps work I can do, I wonder if we can use the label for beginner, etc...

**Comment by vaind** [comment]
Sorry for the later reply. Web support isn't exactly a beginner level issue, maybe start with one of these: https://github.com/objectbox/objectbox-dart/labels/good%20first%20issue

**Comment by vaind** [comment]
Closing this "meta issue" so that the rest of the conversation takes place in the actual, if you choose to contribute to any

**Comment by richard457** [comment]
I am now confident with the codebase, Now Need help in running unit testing, I am getting this error Failed to load dynamic library 'lib/objectbox.dll': 126 when an attempt to run unit testing on my windows machine.

**Comment by richard457** [comment]
I added the lib folder with objectbox.dll in it but this did not solve the issue.

**Comment by vaind** [comment]
Have you tried looking at the CI scripts (`.github/workflows/dart.yaml`) - it also runs on windows.

running `./install.sh` in some shell, e.g. "Git Bash" should install the library in the right folder
