### ISSUE TITLE
CI tests for the flutter demo

### ISSUE THREAD

**Issue by vaind** [objectbox/objectbox-dart#26]
We're using GitHub Actions to `pub run test` - execute tests in the `test` folder - see .github/workflows/`

Another workflow should be added to build the flutter demo/example.

**Comment by vaind** [comment]
FYI

Tried running in `cirrusci/flutter:v1.9.1-hotfix.4` but got `No supported devices connected.` 

And after I ran `flutter config --enable-linux-desktop`, I've got 
```
Downloading linux-x64 tools...                                          
Download failed.
URL: https://storage.googleapis.com/flutter_infra/flutter/b863200c37df4ed378042de11c4e9ff34e4e58c9/linux-x64/linux-x64-flutter.zip
Error: 404 Not Found
```

**Comment by greenrobot-team** [comment]
The Flutter examples are currently being built by CI for desktop and mobile. So closing this.

There is a separate issue to test on a mobile simulator/emulator for iOS/Android at #81.
