### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by abadeus-g** [objectbox/objectbox-dart#266]

**Comment by vaind** [comment]
Thanks for the proposal. Currently, there's no plan to introduce another communication platform. Questions should be asked on StackOverflow while issues and feature requests should be raised on GitHub. We've found this helps to keep the discussions topic-oriented and to keep all the information (to a given topic) in one place while making sure no questions go unnoticed. We may revisit this in the future, but for now, this setup has served well.
