### ISSUE TITLE
Changing a model property does not trigger change on a model

### ISSUE THREAD

**Issue by AfricanDev** [objectbox/objectbox-dart#270]
```
@override
  Stream<Customer?> getCustomerByOrderId({required int id}) {
    log.i(id);
    return _store
        .box<Customer>()
        .query(Customer_.orderId.equals(id))
        .watch(triggerImmediately: true)
        .map((query) => query.findFirst());
  }
```
Having a query like that when a property ID change it does reflect, but when another property changes, for example, updatedAt it does not reflect, my expectation is that when a property changes for update it should reflect this watch query let me know if I am making mistake somewhere.

**Comment by richard457** [comment]
@vaind any input on this?

**Comment by vaind** [comment]
Can you show how you're listening to the result stream? The method you choose defines when the stream is subscribed and when is the subscription cancelled.

**Comment by AfricanDev** [comment]
```
StreamBuilder<Customer?>(
                          stream: ProxyService.api.getCustomerByOrderId(
                              id:  model.orders[0].id),
                          builder: (context, snapshot) {
                            //removed the body code here, but I am not unsubscrbing to the stream in any way
}
```

**Comment by AfricanDev** [comment]
When a new model is added, I get a new stream, but when an existing Model changes a property I do not get a new stream.
