### ISSUE TITLE
Is it possible to build a digital wallet 

### ISSUE THREAD

**Issue by dinarpay** [objectbox/objectbox-dart#271]
Is it possible to build a digital wallet
Users can send and receive money without the Internet
Merchants can also be paid quickly

Is the database completely secure and encrypted if it is hosted on users' phones
And the final hosting is on my own computer, where I can turn on the Internet at any time for synchronization.
What is the best way to communicate and send a notification between phones without internet other than Bluetooth and NFC

**Comment by vaind** [comment]
Database-level encryption is currently not available: #221 

Regarding notifications, bluetooth, nfc, ... to me it sounds out of scope, i.e. not something database is supposed to do.

**Comment by vaind** [comment]
Looks answered. Feel free to follow up if it isn't.
