### ISSUE TITLE
Can not get the unit test to run on my local machine

### ISSUE THREAD

**Issue by richard457** [objectbox/objectbox-dart#277]
I am looking to debut into contributing to this amazing project however I am stuck into getting the unit testing to pass on my local machine, I need a unit test to pass before I write any code here are the steps am taking

1. flutter pub get
2. ./tool/init.sh
3. flutter test
4. see the attached result

![1](https://user-images.githubusercontent.com/8529700/124496456-b9c02e00-ddb9-11eb-8763-6a972fee7a9a.PNG)

**Comment by vaind** [comment]
works for me. could you show the beginning of the output in terminal?

**Comment by richard457** [comment]
```00:06 +3 -81: loading E:\demos\flipper-new\objectbox-dart\objectbox\test\query_property_test.dart
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'pub run test --chain-stack-traces'.
00:06 +3 -81: E:\demos\flipper-new\objectbox-dart\objectbox\test\query_property_test.dart: .average [E]
  LateInitializationError: Local 'env' has not been initialized.
  dart:_internal                       LateError._throwLocalNotInitialized
  test\query_property_test.dart 20:18  main.<fn>```

**Comment by vaind** [comment]
the very first log after you manually type `flutter test` to the terminal, not launching it from vscode... 

what you've sent is `00:06 +3 -81`, i.e. after six seconds, three successful tests and 81 failed ones

**Comment by richard457** [comment]
``` flutter test
00:01 +0 -1: loading E:\demos\flipper-new\objectbox-dart\objectbox\test\basics_test.dart [E]
  Failed to load "E:\demos\flipper-new\objectbox-dart\objectbox\test\basics_test.dart": Connection closed before test suite loaded.```

**Comment by vaind** [comment]
> `Connection closed before test suite loaded`

Looks like a broken flutter environment/setup. Maybe try some of solutions shown on Google when searching for that message? https://www.google.com/search?q=Connection+closed+before+test+suite+loaded

Also, `objectbox` lib is a dart project, so you can try using `dart pub get`, `dart test`, instead of `flutter`

**Comment by richard457** [comment]
I tried different ways to fix this including removing flutter and install it. unless there is special set up required please let me know.

**Comment by greenrobot-team** [comment]
Is this still an issue?
