### ISSUE TITLE
Documentation: separate Flutter from Dart

### ISSUE THREAD

**Issue by i3games** [objectbox/objectbox-dart#278]
### Describe the solution you'd like

Separate Flutter Documentation and Dart Documentation, in that order.

### Additional context

Currently the documentation is rather confusing as it is referencing back and forth between pure Dart and Flutter throughout "Sneak Peek" / "Getting Started" / "Example". 

Also it starts with Dart although very likely most users nowadays will look for Flutter documentation.

**Comment by greenrobot-team** [comment]
https://docs.objectbox.io/getting-started should have resolved this.
