### ISSUE TITLE
objectbox.g.dart openStore() function generated null-safety

### ISSUE THREAD

**Issue by ekones** [objectbox/objectbox-dart#279]
After running 'flutter packages pub run build_runner build', null-safety compatible openStore() parameters were created even though my project is not null-safety. It happened after the 1.10 update.

environment:
    
    sdk: ">=2.7.0 <3.0.0"

**Comment by vaind** [comment]
fixed by 34a6568d9a7e8bb112856c69ea78672513ed8a44
