### ISSUE TITLE
Effective Dart

### ISSUE THREAD

**Issue by minikin** [objectbox/objectbox-dart#28]
Why don't use an [Effective Dart](https://dart.dev/guides/language/effective-dart) for this project?
Like [here](https://github.com/objectbox/objectbox-dart/blob/master/lib/src/bindings/constants.dart) for constant names definitions you [break](https://dart.dev/guides/language/effective-dart/style#prefer-using-lowercamelcase-for-constant-names) it.

Thanks!

**Comment by Buggaboo** [comment]
Those are like that due to readability, and how easily they relate to the C-based names at first glance. I personally have always hated camel case. It's refreshing to see snake case. Style is also about maintainability. If the maintainers experience zero problems...

And now to the real issue, emacs or vim?

**Comment by vaind** [comment]
This should probably be supported by setting up a linter & maybe even including in GitHub actions CI so we notice new offending code.

https://dart.dev/guides/language/analysis-options#enabling-linter-rules

**Comment by GregorySech** [comment]
If you need a pre-made linter configuration for Effective Dart a lot of people uses https://pub.dev/packages/pedantic .
There are a handful that are not set by the package but are listed in the README

**Comment by vaind** [comment]
@GregorySech would you like to contribute a PR configuring it?

**Comment by GregorySech** [comment]
Ok, but I'm not sure how to setup the CI part

**Comment by vaind** [comment]
Sure, we've just started using the new [GitHub Actions](https://github.com/features/actions): 
https://github.com/objectbox/objectbox-dart/blob/dev/.github/workflows/dart.yml

**Comment by vaind** [comment]
Any chance we could get the linter to work with Actions? A major PR was merged today and it shows a couple of linter issues so it would be great if we could prevent it

**Comment by GregorySech** [comment]
I can set it up this evening when I get home from work. So approximately in
2 and a half hours.

**Comment by GregorySech** [comment]
I'll also split the two packages in my next PR or the action will always fail. Working on it on the train.

**Comment by vaind** [comment]
I'd say this has been implemented by now so closing, feel free to open an issue/PR with specific areas of improvements
