### ISSUE TITLE
Where is the findUnique?

### ISSUE THREAD

**Issue by Katekko** [objectbox/objectbox-dart#282]
Version:  objectbox: ^1.1.1

![image](https://user-images.githubusercontent.com/13632735/125506406-18569ca6-9254-4fd6-b11b-09038e9eaaa8.png)

But in code I can't find:
![image](https://user-images.githubusercontent.com/13632735/125506470-fa1786d8-b7c4-4fcc-89af-110e8cceaa7b.png)

**Comment by vaind** [comment]
Indeed it was missing... Added in 8c20d35be2123210512c0d252edecb00e600f804
