### ISSUE TITLE
JSON to Entity conversion

### ISSUE THREAD

**Issue by ebelevics** [objectbox/objectbox-dart#291]
So probably the closest issue for my problem I found is https://github.com/objectbox/objectbox-dart/issues/251. But the problem is that the explanation is too abstract without examples.

I have asked this question before in Stackoverflow (see link for details) : https://stackoverflow.com/questions/68541015/objectbox-dart-how-to-pass-json-to-entity-class,

The problem is that I need to convert json to multiple related entity classes. The provided solution is to use **final address= ToOne< Address>()**, but the biggest problem I face that I cannot attach Address model to User via constructor, as it expects me to pass ID as int for objectbox.g.dart purposes.

### Describe the solution you'd like

What I would like is that, I could use separate Entity class for business logic purposes and separate Model class for http json conversion which extends entity class. But as address variable is not part of constructor in Entity, I have no clue how to parse it, without having clear examples. 

Issues related suggested to use freezed, but I would like to have as little code generated files as possible. Although I did use @JsonSerializable for json to model conversion. 

Below I provided example what I wanted to achieve, but unfortunately it seems objectbox.g.dart is generating id values based on constructor too, meaning I can't add objects as parameter or ignore it with @Transient(). The other solution I found without any similar examples is provided in (https://stackoverflow.com/questions/68541015/objectbox-dart-how-to-pass-json-to-entity-class), but I'm wondering isn't there any better and cleaner way.
```
@Entity()
class User {
  @JsonKey(ignore: true)
  int id = 0;

  String email;
  String firstName;
  String lastName;
  String? phoneNumber;
  String? birthday;
  @JsonKey(ignore: true)
  final address= ToOne<Address>();

  User({
    required this.email,
    required this.firstName,
    required this.lastName,
    @Transient() Address? address,
    this.phoneNumber,
    this.birthday,
  }) {
    this.address.target = address;
  }
}
```

**Comment by ebelevics** [comment]
Also by checking freezed package, it's also not clear how do you exactly integrate relations. https://github.com/objectbox/objectbox-dart/issues/229 and most of seen examples shows classes without relation fields.

**Comment by vaind** [comment]
See this work-in-progress PR how this could be achieved (after we add a `ToOne()` constructor): https://github.com/objectbox/objectbox-dart/pull/292/files#diff-1ebfa44bfe9277ffbebc5ae3ddfe7c44969c37590887449b6223416e4fa08f4aR35-R60

and let me know what do you think.

**Comment by ebelevics** [comment]
I'll test it out this weekend for test application mainly. On production app I switched to floor sqlflite generating package as for time being objectbox didn't bring easy solutions for caching objects, especially when relations are involved. But I do agree that type converters (for json JsonConverter) are really neat thing to adapt custom objects, so I will test proposed solution on objectbox this weekend and bring feedback.

**Comment by greenrobot-team** [comment]
Late, but for future reference examples can be found in tests:
- for JSON serialization https://github.com/objectbox/objectbox-dart/blob/main/generator/integration-tests/part-partof/lib/json.dart
- for freezed https://github.com/objectbox/objectbox-dart/blob/main/generator/integration-tests/part-partof/lib/frozen.dart
