### ISSUE TITLE
 Could not find objectbox-android.jar

### ISSUE THREAD

**Issue by nodelinker** [objectbox/objectbox-dart#294]
what's worng with Could not find objectbox-android.jar (io.objectbox:objectbox-android:2.9.2-RC3)?

> Using hardware rendering with device AOSP on IA Emulator. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
> Launching lib\main.dart on AOSP on IA Emulator in debug mode...
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':objectbox_flutter_libs:javaPreCompileDebug'.
> > Could not resolve all files for configuration ':objectbox_flutter_libs:debugCompileClasspath'.
>    > Could not find objectbox-android.jar (io.objectbox:objectbox-android:2.9.2-RC3).
>      Searched in the following locations:
>          http://maven.aliyun.com/nexus/content/repositories/jcenter/io/objectbox/objectbox-android/2.9.2-RC3/objectbox-android-2.9.2-RC3.jar
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 25s

flutter pub.yml

> name: objectbox_demo
> description: An example project for the objectbox-dart binding.
> version: 0.3.0+1
> 
> environment:
>   sdk: ^2.12.0
>   flutter: ^2.0.0
> 
> dependencies:
>   objectbox: ^1.1.1
>   objectbox_flutter_libs: any
>   flutter:
>     sdk: flutter
>   cupertino_icons: any
>   intl: any
> 
> 
> dev_dependencies:
>   build_runner: ^1.1.1
>   objectbox_generator: any
>   flutter_driver:
>     sdk: flutter
>   test: any
> 
> flutter:
>   uses-material-design: true

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.58.2)
[√] Connected device (3 available)

• No issues found!

flutter pub deps --no-dev

> Dart SDK 2.13.4
> Flutter SDK 2.2.3
> objectbox_demo 0.3.0+1
> |-- cupertino_icons 1.0.3
> |-- flutter 0.0.0
> |   |-- characters 1.1.0
> |   |-- collection...
> |   |-- meta...
> |   |-- sky_engine 0.0.99
> |   |-- typed_data 1.3.0
> |   |   '-- collection...
> |   '-- vector_math 2.1.0
> |-- intl 0.17.0
> |   |-- clock 1.1.0
> |   '-- path...
> |-- objectbox 1.1.1
> |   |-- collection 1.15.0
> |   |-- ffi 1.1.2
> |   |-- meta 1.3.0
> |   '-- path 1.8.0
> '-- objectbox_flutter_libs 1.1.1
>     |-- objectbox...
>     '-- path_provider 2.0.2
>         |-- flutter...
>         |-- path_provider_linux 2.0.2
>         |   |-- flutter...
>         |   |-- path...
>         |   |-- path_provider_platform_interface...
>         |   '-- xdg_directories 0.2.0
>         |       |-- meta...
>         |       |-- path...
>         |       '-- process 4.2.1
>         |           |-- file 6.1.0
>         |           |   |-- meta...
>         |           |   '-- path...
>         |           |-- path...
>         |           '-- platform...
>         |-- path_provider_macos 2.0.2
>         |   '-- flutter...
>         |-- path_provider_platform_interface 2.0.1
>         |   |-- flutter...
>         |   |-- meta...
>         |   |-- platform 3.0.0
>         |   '-- plugin_platform_interface 2.0.1
>         |       '-- meta...
>         '-- path_provider_windows 2.0.3
>             |-- ffi...
>             |-- flutter...
>             |-- meta...
>             |-- path...
>             |-- path_provider_platform_interface...
>             '-- win32 2.2.5
>                 '-- ffi...

**Comment by vaind** [comment]
Looks like you have a maven repository override: "http://maven.aliyun.com" that prevents you to get the package from where it actually is, i.e. Maven Central: https://search.maven.org/artifact/io.objectbox/objectbox-android/2.9.2-RC3/aar

**Comment by nodelinker** [comment]
problem solved, thanks. 😀

checkout init.gradle 

delete file

> allprojects{
>     repositories {
>         def ALIYUN_REPOSITORY_URL = 'http://maven.aliyun.com/nexus/content/groups/public'
>         def ALIYUN_JCENTER_URL = 'http://maven.aliyun.com/nexus/content/repositories/jcenter'
>         all { ArtifactRepository repo ->
>             if(repo instanceof MavenArtifactRepository){
>                 def url = repo.url.toString()
>                 if (url.startsWith('https://repo1.maven.org/maven2')) {
>                     project.logger.lifecycle "Repository ${repo.url} replaced by $ALIYUN_REPOSITORY_URL."
>                     remove repo
>                 }
>                 if (url.startsWith('https://jcenter.bintray.com/')) {
>                     project.logger.lifecycle "Repository ${repo.url} replaced by $ALIYUN_JCENTER_URL."
>                     remove repo
>                 }
>             }
>         }
>         maven {
>             url ALIYUN_REPOSITORY_URL
>             url ALIYUN_JCENTER_URL
>         }
>     }
> }
