### ISSUE TITLE
Query.find() doesn't work

### ISSUE THREAD

**Issue by aalleard** [objectbox/objectbox-dart#305]
### Basic info (please complete the following information):

- ObjectBox version: [e.g. 1.1.1]
- Flutter/Dart SDK: flutter 2.2.3
- Null-safety enabled: yes
- Reproducibility: always
- OS: MacOS BigSur (M1 chip)
- Device/Emulator: iPhone 12 Pro Max

### Steps to reproduce

1. Create an Entity, put some 270.000 records in DB
2. Try to load all records at once using method .find()
3. Get nothing

### Expected behavior

All records should be loaded.

### Code

`final box = this._store.box<Synthese>();`

    // Queries
    final queryBuilder = box.query();
    final query = queryBuilder.build();
    final uuidQuery = query.property(Synthese_.uuid);

    // Execute
    final syntheses = query.find();
    final count1 = syntheses.length;
    final uuids = uuidQuery.find();
    final count2 = uuids.length;
    final count3 = query.count();
    final synthesesIDs = query.findIds();
    final count4 = synthesesIDs.length;
    uuidQuery.close();
    query.close();

    debugPrint('$count1 record found'); // 0 record found
    debugPrint('$count2 record found'); // 272294 record found
    debugPrint('$count3 record found'); // 272294 record found
    debugPrint('$count4 record found'); // 272294 record found`

**Comment by vaind** [comment]
Can you please try with this commit? Might be related to not-propagating an error during `query.find()` and it's fixed in that commit. You can specify a dependency override in your `pubspec.yaml`:

```yaml
dependency_overrides:
  objectbox:
    git:
      url: git@https://github.com/objectbox/objectbox-dart.git
      ref: e1ea9b67ccf6225563b7e73c5a129a770359a557
      path: objectbox
  objectbox_generator:
    git:
      url: git@https://github.com/objectbox/objectbox-dart.git
      ref: e1ea9b67ccf6225563b7e73c5a129a770359a557
      path: generator

**Comment by aalleard** [comment]
Thanks it works, juste had to change a bit your code removing the 'git@'.

Will it work without the override in a near future?

Thanks again

**Comment by vaind** [comment]
Yes, it should come out in the next release. 

Was there an exception somewhere after switching or it just works?

**Comment by aalleard** [comment]
No, it just worked fine :)

**Comment by vaind** [comment]
in that case v1.2 should work for you - you can remove the override and update
