### ISSUE TITLE
windows 11 : Invalid argument(s): Failed to load dynamic library 'lib/objectbox.dll': error code 1497360904

### ISSUE THREAD

**Issue by gcxfd** [objectbox/objectbox-dart#323]
windows 11 
Dart SDK version: 2.15.0-208.0.dev (dev) (Mon Oct 11 22:12:57 2021 -0700) on "windows_x64" ( use `choco install dart-sdk --pre -y` install )
objectbox dart latest

```
final store = openStore();     
```

error
```
Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'lib/objectbox.dll': error code 1497360904
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      _tryObjectBoxLibFile (package:objectbox/src/native/bindings/bindings.dart:56:27)
#3      loadObjectBoxLib (package:objectbox/src/native/bindings/bindings.dart:66:12)
#4      C (package:objectbox/src/native/bindings/bindings.dart:84:27)
#5      C (package:objectbox/src/native/bindings/bindings.dart)
#6      new Model (package:objectbox/src/native/model.dart:19:31)
#7      new Store (package:objectbox/src/native/store.dart:105:21)
#8      openStore (package:rmw/objectbox.g.dart:45:5)
#9      init (package:rmw/init.dart:59:17)
<asynchronous suspension>
#10     main (file:///C:/Users/z/git/rmw/bin/rmw.dart:29:3)
<asynchronous suspension>
```

**Comment by gcxfd** [comment]
yes i installed, see the image below
![image](https://user-images.githubusercontent.com/69608605/137852009-632557ce-1489-42d6-a73f-9ee72d2e6fc5.png)

**Comment by greenrobot-team** [comment]
Works for me using the same file, also inside a `lib` subfolder. Though I am on Windows 10 64-bit.

The returned error codes are also unexpected and do not lead to any useful info.

Can you try to run the [benchmark app inside this repo](https://github.com/objectbox/objectbox-dart/tree/main/benchmark) (it's Dart only), e.g. inside the `benchmark` folder run `dart run bin/read.dart`? Then we can be sure it isn't an issue with your code or setup.

**Comment by richard457** [comment]
This is also happening here https://github.com/objectbox/objectbox-dart/issues/346 on android @greenrobot-team

**Comment by greenrobot-team** [comment]
@richard457 The error message in #346 is completely different. Doubt this is related.

**Comment by greenrobot-team** [comment]
Closing because this issue is missing details. Feel free to comment with additional details and we can re-open it.

**Comment by claudiu-bele** [comment]
I encountered a similar issue with another number trying to load a .dll
```
Failed to load dynamic library 'win_x64/sqlite3.dll': error code 1329587768 
```
Solution: place .dll in root folder and remove the `lib` from the path, like
```
DynamicLibrary _openOnWindows() {
  final corePath = 'sqlite3.dll';
  return DynamicLibrary.open(corePath);
}
```
