### ISSUE TITLE
cloning and equality

### ISSUE THREAD

**Issue by SogoGolf** [objectbox/objectbox-dart#332]
sorry to raise this here but i couldnt find anything on github re objectbox for this hope thats ok. by the way, we are loving objectbox for Flutter ! going to be used in a soon to be released app for LOTS of Australian golfers.

anyway the question is this (and i know it might be pure Dart related, but wanted to see if Objectbox offer anything here):
- we have a box "SelectedComps" lets say with 2 x rows.
- now we want to clone that box, so later on we can do an equality comparison. 

for example lets say we add 1 new row to the "SelectedComps" box. later, we want to know what the difference is between the SelectedComps box (ie now 3 x rows) and the original clone (2 x rows).

what do you suggest is the best way to achieve this ? eg is there an ObjectBox API equality comparison between two boxes? or should we just use Dart to get what we need ? etc

**Comment by NaikSoftware** [comment]
i would do like this: would create schema ItemsStorage `{ @ToMany List<SelectedComp>}`, then fetch one ItemsStorage from the box, create new with other items and store and then fetch and compare them (with overriden == operator or helper function)

**Comment by SogoGolf** [comment]
thanks @NaikSoftware ! For now we've got by just using plain Dart List comparisons. I noticed ObjectBox marked this as an enhancement - can someone at Objectbox comment on what's planned ?

**Comment by NaikSoftware** [comment]
@SogoGolf  i think this label just added automatically:)
