### ISSUE TITLE
We can not update  a field of a class

### ISSUE THREAD

**Issue by venky9885** [objectbox/objectbox-dart#344]
How can we update field of a class using objectbox

consider class below

```
@Entity()
class Person{
@Id()
int id;
String?  name;
String ? adress;
Person({this.id,.....});
}
```
In above class  i need to update only address without name 
which  is to be done for thousands of records in faster time

**Comment by vaind** [comment]
You cannot update a single field, the whole object is always written. However, ObjectBox is capable of [updating hundreds of thousands of objects per second](https://objectbox.io/objectbox-dart-flutter-v0-11-database-performance-relations/) on a mobile phone. Just use [https://docs.objectbox.io/transactions] to group your updates to a single disk write. Or use `Box`'s `putMany()` or `putAsync()` which does it for you.

**Comment by venky9885** [comment]
Ok, I agree with that!!
if possible please update this feature ,Thanks
