### ISSUE TITLE
DateTime comes in UTC if getAll is used but comes with Local if searched through query

### ISSUE THREAD

**Issue by gcostaapps** [objectbox/objectbox-dart#345]
Hi, I'm saving an entity that has a DateTime field. If I query back using findAll() the entity is returned with the field in utc format (as it was saved). But when I search based on query (I'm querying the date field), the return type comes in local timestamp. 

### Basic info (please complete the following information):

- ObjectBox version: 1.3.0
- Flutter/Dart SDK: 2.5.3
- Null-safety enabled: yes 
- Reproducibility: always
- OS: Windows 10 
- Device/Emulator: Windows

### Expected behavior

DateTimes should come always in UTC or always in Local timestamp

### Code

My Entity
```
class RecordDto {
  int id;
  DateTime startDate;
  DateTime endDate;
  int durationInMilliseconds;
  String? comment;
 ......
}
```

How I query the date
```
_queryByYearAndMonth = database.store
            .box<RecordDto>()
            .query(
              RecordDto_.startDate.greaterOrEqual(
                    DateTime.utc(2021, 1).millisecondsSinceEpoch,
                  ) &
                  RecordDto_.endDate.lessOrEqual(
                    DateTime.utc(2021, 2).millisecondsSinceEpoch,
                  ),
            )
            .build()

final result = _queryByYearAndMonth.find();
```

**Comment by gcostaapps** [comment]
Sorry, I think I was doing something weird in my code, I'm now testing and everything works.

**Comment by greenrobot-team** [comment]
You might be interested in reading #308. DateTime is stored without time zone information in ObjectBox. It is currently always read back in local time, regardless if the put DateTime was in local time or UTC.
