### ISSUE TITLE
update dart ffi to ffi ^1.1.2

### ISSUE THREAD

**Issue by richard457** [objectbox/objectbox-dart#347]
Allow the package to work well with the latest ffi play nice with other package.

**Comment by vaind** [comment]
The specification is already `ffi: ^1.0.0` witch also matches the latest version as of today, v1.1.2. 

Increasing the dependency requirement is actually going to cause the opposite of what you're saying: it would limit the number of compatible packages (i.e. to only those that also can work with ffi 1.1.2)

**Comment by greenrobot-team** [comment]
Closing because this issue is missing details. Feel free to comment with additional details and we can re-open it.
