### ISSUE TITLE
Variable DateTime with annotation @Property(type: PropertyType.date) is getting updated by itself

### ISSUE THREAD

**Issue by raphire08** [objectbox/objectbox-dart#348]
:rotating_light: First, please check:

Start with a clear and concise problem description in English. Then provide the following information, please.

- ObjectBox version: [e.g. 0.14.0]
1.2.0

- Flutter/Dart SDK: [e.g. 2.0.0, or the output of `dart --version` or `flutter --version`]

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (5 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

- Null-safety enabled: [yes | no]
Yes

- Reproducibility: [e.g. occurred once only | occasionally without visible pattern | always]
Always

- OS: [e.g. Linux 5.10.23 | Windows 10 | macOs BigSur | Android 10 | ... ]
macOS Monterey

- Device/Emulator: [e.g. Galaxy S20]
iOS 14.4 simulator

### Steps to reproduce

1. Make any schema having DateTime variable, and annotation as PropertyType.date

2. Create and save two new data, note down the DateTime variable being created

3. Update DateTime variable in one reading and save it, and now read the second reading.

DateTime variable in second reading is changed automatically

### Expected behavior
DateTime variable should not change in second reading,

**Comment by greenrobot-team** [comment]
@raphire08 Can you please share the code that puts and gets the objects? I suspect it's simply getting the same object?

**Comment by raphire08** [comment]
@greenrobot-team 

I hope that something should be amiss on my side only. Give me sometime, I will try to reproduce it in some simpler object and share the code for same.

**Comment by greenrobot-team** [comment]
@raphire08 OK, thanks. I will close this issue for now as there is nothing for us to do. Feel free to re-open or create a new one.
