### ISSUE TITLE
Ability to compile project with objectbox for web wihout ffi issues

### ISSUE THREAD

**Issue by richard457** [objectbox/objectbox-dart#359]
I want to compile my code for the web, some part of its web, I know the web is not supported but at least compiling the project containing objectbox shouldn't fail.
I tried this
```import 'init.dart'
    if (dart.library.html) 'web_init.dart'
    if (dart.library.io) 'io_init.dart';
``` 
but obviously, this can not work especially when dealing with models any idea on how I can achieve this?

**Comment by vaind** [comment]
See the answare here: https://github.com/objectbox/objectbox-dart/issues/283#issuecomment-879831661
