### ISSUE TITLE
Box provide missing methods

### ISSUE THREAD

**Issue by vaind** [objectbox/objectbox-dart#36]
Box already has get/put as well as their bulk variants. To be more up to par with the rest of the bindings, the following methods should be implemented:

* [x] count(optional limit)
* [x] contains(id)
* [x] isEmpty()
* [x] remove(id)
* [x] removeAll()

See [box.go](https://github.com/objectbox/objectbox-go/blob/master/objectbox/box.go) and [go docs](https://godoc.org/github.com/objectbox/objectbox-go/objectbox#Box) for reference

**Comment by vaind** [comment]
Thank you @liquidiert :+1: I've merged the PR after resolving some issues caused by the huge query PR changelist.

Could you maybe have a look at the last method (or two): `contains(id), containsMany(ids)` since you're already familiar with the code and its tests. If so, please start it on a new branch based on the latest `dev` to prevent merge conflicts, as there have been major changes today.

**Comment by liquidiert** [comment]
Of course :+1: I'm happy to help 😄

**Comment by vaind** [comment]
thanks for implementing this @liquidiert :tada:
