### ISSUE TITLE
Evaluate FB `asciiOptimization: true` with latest Dart/Flutter

### ISSUE THREAD

**Issue by vaind** [objectbox/objectbox-dart#360]
See TODOs in code_chunks.dart  https://github.com/objectbox/objectbox-dart/pull/349#discussion_r772314275_

The [Dart SDK issue](https://github.com/dart-lang/sdk/issues/39843) is resolved now by https://dart-review.googlesource.com/c/sdk/+/221467 - after it's part of the released SDK, check the influence on benchmarks

**Comment by Vahid1919** [comment]
`asciiOptimization: true` performs much better overall. I noticed that the first time I run it with `asciiOptimization: true`, the `readAll` takes about 8 ms and then decreases with each run until it stabilises around 6ms after I run it multiple times.
With `asciiOptimization: false` it is more random and stays between 7-9ms.

<img width="701" alt="image" src="https://user-images.githubusercontent.com/63849626/178267538-dd2f83d6-efbb-4bd3-863c-4b9828465b75.png">

**Comment by greenrobot-team** [comment]
Updated TODOs, closing this then.
