### ISSUE TITLE
Unable to Open Store Using Default Directory (Flutter)

### ISSUE THREAD

**Issue by scottbisaillon** [objectbox/objectbox-dart#363]
I am getting the following exception on startup when trying to open the store using the generated method `openStore()`. I am not specifying the directory to use.

```
Exception has occurred.
_CastError (Null check operator used on a null value)
```

This appears to be happening in the `path_provider` package when calling this method:
```dart
Future<Directory> getApplicationDocumentsDirectory() async {
  final String? path = await _platform.getApplicationDocumentsPath();
  ...
}
```

### Basic info

- ObjectBox version: 1.3.0
- Flutter/Dart SDK: 2.5.3 (also tried with 2.8.1)
- Null-safety enabled: yes
- Reproducibility: always
- OS: Android 10
- Device/Emulator: Physical device - Samsung S9+

### Logs, stack traces

Here is the full stack trace for reference.

```bash
E/flutter (17105): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (17105): #0      MethodChannel.binaryMessenger
package:flutter/…/services/platform_channel.dart:121
E/flutter (17105): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:146
E/flutter (17105): #2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:329
E/flutter (17105): #3      PathProviderAndroid.getApplicationDocumentsPath
package:path_provider_android/path_provider_android.dart:39
E/flutter (17105): #4      getApplicationDocumentsDirectory
package:path_provider/path_provider.dart:115
E/flutter (17105): #5      defaultStoreDirectory
package:objectbox_flutter_libs/objectbox_flutter_libs.dart:10
E/flutter (17105): #6      openStore
package:dashboard_data_source/objectbox.g.dart:52
E/flutter (17105): #7      ObjectBoxDashboardDataSource.init
package:dashboard_data_source/src/objectbox_dashboard_data_source.dart:43
E/flutter (17105): #8      main
package:personal_tracker/main_development.dart:11
E/flutter (17105): #9      main
.dart_tool\flutter_build\generated_main.dart:80
E/flutter (17105): #10     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:143:38)
E/flutter (17105): #11     _rootRun (dart:async/zone.dart:1428:13)
E/flutter (17105): #12     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (17105): #13     _runZoned (dart:async/zone.dart:1863:10)
E/flutter (17105): #14     runZonedGuarded (dart:async/zone.dart:1851:12)
E/flutter (17105): #15     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:141:5)
E/flutter (17105): #16     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (17105): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (17105):
```

**Comment by vaind** [comment]
Have you tried calling `path_provider`'s `getApplicationDocumentsDirectory()` directly from your app? If it also fails, it's the issue in the package. That's what this looks like to me at the moment, based on the stack trace.

**Comment by vaind** [comment]
Also, check if calling `WidgetsFlutterBinding.ensureInitialized();` (before the path_provider is called) helps.

**Comment by scottbisaillon** [comment]
> Also, check if calling `WidgetsFlutterBinding.ensureInitialized();` (before the path_provider is called) helps.

So this ended up being the issue. I _was_ calling `WidgetsFlutterBinding.ensureInitialized();`, however, it was after trying to open the store. 

My confusion was when trying another similar package that worked. Looking into theirs a little closer, it appears calling their `initFlutter()` method actually calls `WidgetsFlutterBinding.ensureInitialized();` before getting the directory.

Thanks for the help!
