### ISSUE TITLE
Close the query after subscription is cancelled in QueryBuilder.watch

### ISSUE THREAD

**Issue by i7berezovsky** [objectbox/objectbox-dart#365]
It looks like you are not closing the query after subscription is cancelled:
https://github.com/objectbox/objectbox-dart/blob/5086d4ce0261f856a107afdcacadd2b59da478ce/objectbox/lib/src/native/query/builder.dart#L50

[Doc says](https://github.com/objectbox/objectbox-dart/blob/5086d4ce0261f856a107afdcacadd2b59da478ce/objectbox/lib/src/native/query/builder.dart#L28) that query is closed when user cancel the subscription.
So I think onCancel should also call `query.close()`;

**Comment by greenrobot-team** [comment]
Thanks for reporting! The docs are not up to date. This was the previous behavior. Since `0.15.0` the query can be re-used even if the subscription is cancelled. It is auto-closed using a finalizer. See https://github.com/objectbox/objectbox-dart/pull/240/files

**Comment by i7berezovsky** [comment]
So query will be closed automatically by garbage collector, right?

**Comment by greenrobot-team** [comment]
@i7berezovsky Yes! But you can still manually call `close()` to free resources earlier.

**Comment by i7berezovsky** [comment]
Thank you for clarifying.

**Comment by greenrobot-team** [comment]
Docs will be updated with next release.
