### ISSUE TITLE
Share the database between two applications

### ISSUE THREAD

**Issue by ziaratban** [objectbox/objectbox-dart#367]
Is there a plan in `ObjectBox` to share the database between applications?

**Comment by greenrobot-team** [comment]
What exactly do you mean by share? Can you give an example? If this is about using the database across different processes then the answer is likely no.

**Comment by ziaratban** [comment]
I want to share the database between a service and my applications on android platform.
This feature does not appear to be fully supported by ObjectBox. ([more](https://github.com/objectbox/objectbox-java/issues/193))
If you have another solution, please open this issue again and I will be happy.

Thanks.
