### ISSUE TITLE
error :lastRelationId 1:3314524755426469575 does not match any standalone relation

### ISSUE THREAD

**Issue by visign3d** [objectbox/objectbox-dart#370]
After deleting some old entitys ,with relations this error is thrown after build runner : 
```
lastRelationId 1:3314524755426469575 does not match any standalone relation
```

**Comment by greenrobot-team** [comment]
Check that the `lib/objectbox-model.json` file of your project contains a `retiredRelationUids` property that includes the UIDs of the removed relations.

If only the relation you mentioned is removed, this should look something like:
```
  "retiredRelationUids": [
    3314524755426469575
  ],
  "version": 1
}
```

It's possible this section got removed by accident e.g. when merging branches. If you do not believe so I'd like to know the steps that lead to this state.

**Comment by visign3d** [comment]
It was only changed in Android Studio ,by myself. I had three boxes with three different entity's. Two of them ,with relations were deleted. We can close this issue for now , because i had accidentally regenerated the object-model.json ,which is forbidden, but it solved the problem for now. I will open another issue if have a similar problem in the future.

**Comment by greenrobot-team** [comment]
Alright, thanks for getting back! Closing this then.
