### ISSUE TITLE
See/Edit database .mdb file

### ISSUE THREAD

**Issue by gcostaapps** [objectbox/objectbox-dart#374]
I see in the docs that there is a way to see the database only for Java/Kotlin on Android. Is there any other way to see/open/edit the database (.mdb) ? Will it be possible for flutter applications in near future?

**Comment by greenrobot-team** [comment]
Not right now, but support for ObjectBox Admin (previously known as Data Browser) is coming for Flutter: see #148.

A tedious workaround is to copy the database file to an Android app that just opens it and starts the data browser.
