### ISSUE TITLE
Request to update generator analyser from   analyzer: '>=1.1.0 <3.0.0' to   analyzer: '>=1.1.0 <3.2.0'

### ISSUE THREAD

**Issue by richard457** [objectbox/objectbox-dart#380]
With current constraints, it is hard to use the object box generator alongside with other generator that use the latest analyser. @greenrobot @vaind

**Comment by richard457** [comment]
@greenrobot @vaind

**Comment by greenrobot-team** [comment]
Thanks! Will look into this for the next release.

**Comment by richard457** [comment]
@greenrobot-team can we have this pushed to dev for example so we can install it, we are kinda stack with this waiting too long for the update. @vaind

**Comment by greenrobot-team** [comment]
@richard457 New analyzer version constraint now released as part of `1.4.0`. Let us know if this works for you!
