### ISSUE TITLE
File package:objectbox/flatbuffers/flat_buffers.dart cannot be found on 1.4.0

### ISSUE THREAD

**Issue by orestesgaolin** [objectbox/objectbox-dart#389]
Using Objectbox 1.4.0 causes problem with resolving flatbuffers file.

```
Error: Error when reading '../../../../../.pub-cache/hosted/pub.dartlang.org/objectbox-1.4.0/lib/flatbuffers/flat_buffers.dart': No such file or directory
import 'package:objectbox/flatbuffers/flat_buffers.dart' as fb;
```

The same code works with 1.3.0.

### Basic info (please complete the following information):

- ObjectBox version: 1.4.0
- Flutter/Dart SDK: stable 2.10.0, Dart 2.16
- Null-safety enabled: yes
- Reproducibility: yes

### Steps to reproduce

1. Create new objectbox model with 1.3.0
2. Update to use 1.4.0
3. See the above error when trying to run the app or run tests for the package using objectbox

### Expected behavior

The file should be present

### Logs, stack traces

```
Run flutter test --no-pub --coverage --test-randomize-ordering-seed random
  flutter test --no-pub --coverage --test-randomize-ordering-seed random
  shell: /usr/bin/bash -e {0}
  env:
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter
    PUB_CACHE: /home/runner/.pub-cache


00:00 +0: loading /home/runner/work/[redacted]/packages/database_client/test/src/database_client_test.dart                                                                            
../models/lib/objectbox.g.dart:[7](https://github.com/[redacted]/runs/5317216736?check_suite_focus=true#step:7:7):[8](https://github.com/[redacted]/runs/5317216736?check_suite_focus=true#step:7:8): Error: Error when reading '../../../../../.pub-cache/hosted/pub.dartlang.org/objectbox-1.4.0/lib/flatbuffers/flat_buffers.dart': No such file or directory
import 'package:objectbox/flatbuffers/flat_buffers.dart' as fb;
       ^
```

**Comment by scalz** [comment]
I solved this error by regenerating objectbox.g.dart

**Comment by greenrobot-team** [comment]
Thanks @scalz! [Added at least a note to GitHub release notes](https://github.com/objectbox/objectbox-dart/releases/tag/v1.4.0) (pub.dev change log can't be changed after release).
