### ISSUE TITLE
Get a dynamic view on the objectbox data for migration

### ISSUE THREAD

**Issue by khainke** [objectbox/objectbox-dart#391]
Currently there is no consistent solution how to approach data migration for the flutter objectbox. There is some automatic migration, but some use cases are not covered by this. This includes:
- changing the type of a field
- changing individual values of entries / rows via a conversion method
- transfering / calculating values of new fields based on old ones
- workflow for data transfer between multiple versions

To implement a custom solution, it would help, if we could get a view on the data of the objectbox, that does not require a typed model. Currently such a model is generated for a specific version to `objectbox.g.dart`. A call to `openStore` and `box()` relies on that specific version of the model. This means for a transition between versions, one has to use every generated `objectbox.g.dart` in between 2 versions and every class definition of "Entities" between these 2 versions. This is tedious. 

### Describe the solution you'd like
An access to the objectbox data, which presents the data as jsonLike / `dynamic` / `Map<String, dynamic>`. This could help to write custom migration logic, that does not require model and entity definitions. One will lose type safety, but this is not uncommon with migration logic.
This could be archieved by having knowledge of the entity id: 
```dart
final entityId = 10000000;
final box = store.dBox(entityId);
// get dynamic view on entries in the box
final List<Map<String, dynamic>> entries = box.getAll();
// manipulate data, if possible
entries[0]['x'] = 12;
box.put(entries[0]);
```

**Comment by greenrobot-team** [comment]
Thanks! Maybe have a look at https://docs.objectbox.io/advanced/data-model-updates

And already trying to poke a hole in this suggestion: what use case requires to use two different models? Just use the latest one and write some migration logic? E.g. declare an "old" property as deprecated and only use the new one in your code.

**Comment by khainke** [comment]
While you're essentially right, it is a bit troublesome to collect more and more deprecated, unused definitions over time in the domain model. 
Also, the names of these deprecated fields are blocked. Naming of new properties is often suboptimal to the original name. But one might work with Property Id annotations and renamings to target this problem.
But, constructing entities with deprecated fields could be troublesome if these properties are non-nullable. One could supply a default value in the constructor, but its all a bit unintuitive. 
Essentially, the idea is to never really remove a field, when you want to use it in migration logic. Nor you should change the type of a field. Just work with renaming and write migration logic around your app? Feels a bit off, coming from more traditional databases with explicit migration steps, but i'll try and see.

**Comment by greenrobot-team** [comment]
Thanks for your additional thoughts!

> coming from more traditional databases

I guess. ObjectBox focuses on using classes/code. So it might make sense to think more in coding terms, e.g. `@Entity` classes are public API. Then a migration is more like deprecating old API and adding new ones.
