### ISSUE TITLE
how to update ToOne in flutter?

### ISSUE THREAD

**Issue by joo6077** [objectbox/objectbox-dart#396]
Hi, I'm wondering how to update 1:1 relation in flutter

I could check there is Java/Kotlin in the docs.

is there nothing like setTarget() in flutter?

    @Entity()
    class HomeModel {
      int? id;
    
      final repentance = ToOne<HomeModelObject>();
      final fiveKindsOfIncense = ToOne<HomeModelObject>();
      final mantraDharani = ToOne<HomeModelObject>();
      final meritTransference = ToOne<HomeModelObject>();
      final greatVow = ToOne<HomeModelObject>();
      final vajradhatuMandala = ToOne<HomeModelObject>();
    }

    @Entity()
    class HomeModelObject {
      int? id;
    
      final String name;
      final int orderNum;
      final int count;
    
      HomeModelObject({
        this.id,
        required this.name,
        required this.orderNum,
        this.count = 1,
      });

      final homeBox = _store.box<HomeModel>();

      final homeModel = homeBox.get(1);
      homeModel!.repentance.target =
          homeModel.repentance.target!.copyWith(count: 99);
      homeBox.put(homeModel);

when I try this, it always create new HomeModelObject.

I just want to update one field of HomeModel property which is ToOne relation.

Thanks!

**Comment by greenrobot-team** [comment]
```
homeModel!.repentance.target =
      homeModel.repentance.target!.copyWith(count: 99);
homeBox.put(homeModel);
```
> when I try this, it always create new HomeModelObject.

This is exactly what this code does. It creates a new `HomeModelObject` and puts the new one.

First some clarification: `ToOne` only keeps track of the relation. That it inserts a new target object is just for convenience. So to update a target object, somehow obtain that object, update its properties and put it into its box.

In your case `HomeModelObject` appears immutable, so this requires some work. Basically, construct a new object that has the same ID, put that (it will replace the existing object with that ID), then refresh the resolved target. This can look something like this:
```dart
// Get and update related object
final repentance = homeModel!.repentance.target!;
final repentanceCopy = repentance.copyWith(id: repentance.id, count: 99);
_store.box<HomeModelObject>().put(repentanceCopy);

// get homeBox 1 again to update its ToOne relations
final updatedHomeModel = homeBox.get(1);
```

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to comment with more information or create a new issue.

**Comment by stvhrs** [comment]
u need to create new class, toOne can't detected if its has the same id and then update it, instead i replace it,
 widget.customer.spk.target = Spk(customerName: 'New Class',);

**Comment by greenrobot-team** [comment]
@stvhrs If you want to update the properties of a target object, then put the changes using its box (here `Box<Spk>`).

That ToOne puts a target object if it has no ID set is just for convenience. ToOne is only meant to track the relation to a target object, e.g. reference another object via ID.
