### ISSUE TITLE
Query with linkMany does not provide value if there are no entities in ToMany relation

### ISSUE THREAD

**Issue by orestesgaolin** [objectbox/objectbox-dart#403]
### Basic info (please complete the following information):

- ObjectBox version: 1.4.1
- Flutter/Dart SDK: 2.10.3
- Null-safety enabled: yes
- Reproducibility: yes, sample available here
- OS: Android, iOS, macOS
- Device/Emulator: n/a

### Steps to reproduce

Example [available here](https://github.com/objectbox/objectbox-dart/pull/402/files)

1. Add several attachments to the first note by clicking on the attachment icon, don't add them to other notes

![screenshot_2022-03-23_13 36 43](https://user-images.githubusercontent.com/16854239/159700687-34529f43-2d1c-4dad-9770-25586a0e1040.png)

2. Update query for a Note entity that has ToMany relation using `..linkMany(Entitiy_.relation)`

```dart
  ObjectBox._create(this.store) {
    noteBox = Box<Note>(store);

    final qBuilder = noteBox.query()
      ..order(Note_.date, flags: Order.descending)
      // Comment to see it working
      ..linkMany(Note_.attachment);
    queryStream = qBuilder.watch(triggerImmediately: true);

    // Add some demo data if the box is empty.
    if (noteBox.isEmpty()) {
      _putDemoData();
    }
  }
```

4. Hot restart the app
5. Observe that it doesn't emit values which have no entities in the above relation

![screenshot_2022-03-23_13 37 09](https://user-images.githubusercontent.com/16854239/159700771-494d75f8-e33e-4e9e-ab3f-62927c854341.png)

6. Comment out line 23 in `objectbox.dart` file, hot restart the app, and observe this entity to be shown again

### Expected behavior

Query using `.linkMany` should emit values also when there are no entities in the ToMany relation

### Code

Sample available here https://github.com/objectbox/objectbox-dart/pull/402/files

**Comment by greenrobot-team** [comment]
Thanks for the report. However, why would you expect `linkMany` without a condition on the related entity to also return objects without related objects? So basically being equivalent to the query without the `linkMany` condition?

Note that typically the link conditions are used with a condition, so e.g. 
`linkMany(Note_.attachment, Attachment_.content.contains("something"))`.

**Comment by orestesgaolin** [comment]
I think I see where my expectation does not meet the reality - I don't pass any condition to the `linkMany` because I want all the possible related objects, even when there are no objects yet. The reason I want to use `linkMany` is that I want to be notified about changes to the related objects as well. In the example with notes and attachments if the attachment name changes, I want this to be reflected in the main query. Without using `linkMany` I won't be notified about the change of the linked attachment name (correct me if there's a different way to achieve that).

The workaround I use right now uses 2 instances of the same query. One of them without `linkMany`, the other with `linkMany`. Then I merge 2 streams with `Rx.merge`. In pseudo code it would be something like:

```dart
    final qBuilder1 = noteBox.query()
      ..order(Note_.date, flags: Order.descending)
      ..linkMany(Note_.attachment);
    final qBuilder2 = noteBox.query()
      ..order(Note_.date, flags: Order.descending);
    return Rx.merge([qBuilder1.watch(triggerImmediately: true), qBuilder2.watch(triggerImmediately: true)])
               .distinct();
```

| Case | Without `linkMany` | With `linkMany` |
| ---- | ---- | ---- |
| 0 related objects | ✅ | ❌ |
| 1 related object | ✅ but does not update when related object changed | ✅ |
| remove last object | ✅ | ❌ does not update the list |
