### ISSUE TITLE
Differently signed dart from brew prevents loading C library

### ISSUE THREAD

**Issue by Buggaboo** [objectbox/objectbox-dart#41]
I got this, by moving the lib one level lower (project root):

```bash
...
 Invalid argument(s): Failed to load dynamic library (dlopen(libobjectbox.dylib, 1): no suitable image found.  Did find:
        libobjectbox.dylib: code signature in (libobjectbox.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
  dart:ffi                                             new DynamicLibrary.open
...
```

It might be a new security thing. [I'm not the only one](https://github.com/dart-lang/sdk/issues/38314). According to this thread, we either need objectbox's or dart's signing key, or remove the signing hash from the compiling dart binary. I fixed it by doing the last bit.

From bash or zsh wherever:
```bash
codesign --remove-signature `which dart`
```

_Originally posted by @Buggaboo in https://github.com/objectbox/objectbox-dart/timeline_

**Comment by vaind** [comment]
There isn't much we can do at the moment. Signing the library wouldn't help either because all libraries need to be signed by the same developer (app publisher).

At least for now, let's wait and see how it's resolved in the Dart SDK issue you've linked

**Comment by vaind** [comment]
I don't think this is an issue anymore with the changes landing in dart/flutter binaries, right? Closing this but feel free to comment in case you think there's something more to be done on objectbox-dart side instead
