### ISSUE TITLE
Add some documentation for deployment with dart compile (dart-native)

### ISSUE THREAD

**Issue by khainke** [objectbox/objectbox-dart#412]
Right now, it is not very clear, how one would deploy a dart-native app that uses objectbox-dart. In my understanding any compiled dart app (`dart compile`), that uses objectbox-dart, will still references the objectbox-c-library installed via 

```
bash <(curl -s https://raw.githubusercontent.com/objectbox/objectbox-dart/main/install.sh)
``` 

Simply copying the app will result in an error, that the objectbox-c library is missing.

### Describe the solution you'd like

Ideally, i would like to be able to bundle the library into the compiled executable. Or if that is not possible, i would like to be able to choose a location or name for the library, so that i can put it somewhere other than the standard installation path.

Maybe there is already a way to do this with `dart compile`, but i didnt see one. In any case, some documentation about how to deploy this for dart-native would be cool.

For flutter, the necessary library is already bundled in a `flutter build` as far as i can tell...

**Comment by ivahnenkoAnna** [comment]
Thanks for pointing out, we will look into this as soon as possible.

**Comment by greenrobot-team** [comment]
Thanks! Yes, the shared library file downloaded with install.sh needs to be shipped with the executable. I'm not aware of a way to bundle shared libraries into a Dart executable.

The objectbox package currently looks in various locations depending on the operating system (using Dart's `DynamicLibrary.open`). See `_tryObjectBoxLibFile()` in [bindings.dart](https://github.com/objectbox/objectbox-dart/blob/main/objectbox/lib/src/native/bindings/bindings.dart#L32).

Based on testing (I haven't found official documentation) `DynamicLibrary.open` looks in:
- Windows: the working directory and `%WINDIR%\system32` directory.
- macOS: `/usr/local/lib` (and maybe others).
- Linux: `/lib` and `/usr/lib` (again, maybe others).

For Windows we have added a fallback to also look in the `lib` subfolder where `install.sh` downloads.

With the next release this will also be done before looking in global folders and for macOS and Linux as well.

We are open to suggestions to improve this!

**Comment by greenrobot-team** [comment]
[The Getting Started page](https://docs.objectbox.io/getting-started) now has some details about shipping the library for Dart command-line apps.

We have not found a way to build e.g. an application bundle. I guess this would be left up to an installer framework.
