### ISSUE TITLE
removing relation not working.. 

### ISSUE THREAD

**Issue by Bikram40** [objectbox/objectbox-dart#416]
// Remove the relation to the first order in the list
Order order = customer.orders.removeAt(0);
store.box<Customer>().put(customer);
// Optional: also remove the order entity from its box:
// store.box<Order>().remove(order);

**Comment by greenrobot-team** [comment]
We have tests covering this works. Can you share a test case that we can use to reproduce this?

**Comment by orestesgaolin** [comment]
I think I have a similar issue. I have and object, let's call it a `Session` that can have `ToMany` videos assigned. If I have 1 video left in the box, and then I put the same `Session` with empty list of videos, the relation is not removed, the video stays there.

I'm trying to build a reproducible example now.
