### ISSUE TITLE
Error when App restarted. Bad state: failed to create store: 10001 Cannot open store: another store is still open using the same path.

### ISSUE THREAD

**Issue by BLB-EN438** [objectbox/objectbox-dart#417]
I am using objectbox:^1.4.1 If we manually closes the app by pressing the device back button and then again open the app from background app, I am still getting this error. Bad state: failed to create store: 10001 Cannot open store: another store is still open using the same path: "/data/data/com.example.name/app_flutter/objectbox".

### Follow below steps to reproduce.
1. Press device(Android) button while running the app.
2. Then Press background stack button (Square or round device button) where we can see all the running apps and select the app.
3. This will throw the error.

https://user-images.githubusercontent.com/90668242/167373346-13da1561-5f8e-4928-997f-139fc9ded971.MOV

**Comment by greenrobot-team** [comment]
Thanks for reporting! However, using [the demo project](https://github.com/objectbox/objectbox-dart/tree/main/objectbox/example/flutter/objectbox_demo) I can not reproduce this. My setup:
- Android 12 emulator (x86_64)
- Flutter 2.10.5

Maybe check how you set up the `Store`, e.g. compare against our demo project for an example.

If all looks fine, maybe share a small example project or details about how `Store` is set up and used in your project.

**Comment by akshay-kapase** [comment]
https://stackoverflow.com/questions/72501459/getting-error-as-unhandled-exception-bad-state-failed-to-create-store-10001#
