### ISSUE TITLE
Web Admin Object box network error

### ISSUE THREAD

**Issue by karminq** [objectbox/objectbox-dart#427]
- ObjectBox version: 1.5.0
- Flutter/Dart SDK: Flutter 3.0.1 / Dart 2.17.1
- Null-safety enabled: yes
- OS: macOs Big Sur
- Device/Emulator: Honor 8x / emulator Pixel xl2 api 29 

* `flutter doctor -v`
![Снимок экрана 2022-05-24 в 11 23 43](https://user-images.githubusercontent.com/92505756/169985111-3997d800-19c1-4903-8c2a-12e6208c5e37.png)

### Steps to reproduce
build graddle
![Снимок экрана 2022-05-24 в 11 25 09](https://user-images.githubusercontent.com/92505756/169985573-30851a8c-8514-43da-b5ac-7740094a2fd8.png)

androidManifest
![Снимок экрана 2022-05-24 в 11 25 33](https://user-images.githubusercontent.com/92505756/169985659-65eff91a-9d91-4ce3-a959-409387fcd2ab.png)

main.dart
![Снимок экрана 2022-05-24 в 11 26 44](https://user-images.githubusercontent.com/92505756/169985895-f95ef7ab-758e-4db7-a026-5b3954ef2c21.png)

pubspec.yaml

dependencies
![Снимок экрана 2022-05-24 в 11 27 36](https://user-images.githubusercontent.com/92505756/169986072-5910f2bb-066b-4070-b507-0ef98b11594a.png)

dev dependencies
![Снимок экрана 2022-05-24 в 11 28 00](https://user-images.githubusercontent.com/92505756/169986192-bfac3352-d555-44bd-b702-6d5243c5a13b.png)

log 
![Снимок экрана 2022-05-24 в 11 29 03](https://user-images.githubusercontent.com/92505756/169986435-89461508-db1d-4edb-95a8-33f1b4f5a7c4.png)

Error on web
![Снимок экрана 2022-05-24 в 11 32 29](https://user-images.githubusercontent.com/92505756/169987178-3805827d-51e7-4ca8-a778-836e9d2e7a62.png)

After adb forward, I click on the link from the terminal. After a couple of seconds, the application crashes, the 'Network Error' error is displayed on the web

**Comment by greenrobot-team** [comment]
Thanks for reporting, but I can't reproduce. E.g. I added Admin to our new example (https://github.com/objectbox/objectbox-dart/pull/428) and it works as expected.

Some notes:
- remove the `implementation` dependency,
- remove the permissions from your manifest (they are added automatically by depending on the browser library)

Source: https://docs.objectbox.io/data-browser

Is it possible that `_admin` is somehow garbage collected or the app stops? If you can't resolve the crash, it would help us to reproduce this issue if you can submit a minimal example project.

**Comment by karminq** [comment]
Sorry, my mistake. I created the ObjectBox class but didn't initialize it. Used your challenge with adding Admin and everything is working for the moment
