### ISSUE TITLE
Exception: Unable to generate build files

### ISSUE THREAD

**Issue by bulsond** [objectbox/objectbox-dart#431]
- ObjectBox version: 1.5.0
- Flutter/Dart SDK: Flutter 3.0.1 / Dart SDK version: 2.17.1 (stable) (Tue May 17 17:58:21 2022 +0000) on "linux_x64"
- Null-safety enabled: yes
- Reproducibility: always
- OS: `Linux 5.13.0-44-generic #49~20.04.1-Ubuntu`
- Device/Emulator: no

After adding the dependency `objectbox_flutter_libs: ^1.5.0`, the project is not compiled for desktop linux.

The error is `Launching lib/main.dart on Linux in debug mode...
CMake Error at flutter/ephemeral/.plugin_symlinks/objectbox_flutter_libs/linux/CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.11 or higher is required.  You are running version 3.10.2
Exception: Unable to generate build files
Exited (sigterm)`

**Comment by greenrobot-team** [comment]
`CMake 3.11 or higher is required. You are running version 3.10.2`

You need to install a more recent version of CMake.

Let us know if that doesn't resolve your issue.

**Comment by bulsond** [comment]
I already had version 3.16.3 at the time of this error.
![screenshot](https://user-images.githubusercontent.com/2641410/173387143-99b154c4-9be1-45e9-b60f-b015410552db.png)

**Comment by greenrobot-team** [comment]
Are you maybe using Flutter via a snap? It is known to bundle an outdated version of CMake: https://github.com/objectbox/objectbox-dart/issues/317

If so, try to install Flutter "regularly" by downloading the SDK.

**Comment by bulsond** [comment]
Thanks for the hint.

**Comment by greenrobot-team** [comment]
@bulsond Did that resolve your issue?

Side-note: I added a hint about this on the [Getting Started page](https://docs.objectbox.io/getting-started).

**Comment by bulsond** [comment]
Thanks. Yes, I reinstalled flutter and after that everything worked.

**Comment by greenrobot-team** [comment]
Closing this then.
