### ISSUE TITLE
Unhandled Exception: Bad state: failed to create store: 10001 Cannot open store: another store is still open using the same path:

### ISSUE THREAD

**Issue by akshay-kapase** [objectbox/objectbox-dart#433]
### Basic info (please complete the following information):

- ObjectBox version: 1.5.0
- Flutter/Dart SDK: Flutter 2.10.5 • channel stable Dart 2.16.2 • DevTools 2.9.2
- Null-safety enabled: [yes]
- Reproducibility: occurs every time I click on the notification
- OS: All versions
- Device/Emulator: Pixel 3a Api 32

### Steps to reproduce

1. I'm using moengage library for push notifications. When the notification is clicked the main function is called.
2. Notification is clicked while the app is running, then after that store is getting as null and if "await openStore" is called its causing an error showing "Store is already open"

### Expected behavior

Store should not be null.

### Code

If applicable, add code to help explain your problem.

- Include your pubspec.yaml.
   objectbox: 1.5.0
   objectbox_flutter_libs: 1.5.0

### Logs, stack traces

Unhandled Exception: Bad state: failed to create store: 10001 Cannot open store: another store is still open using the same path:

**Comment by greenrobot-team** [comment]
Modify your code so it ensures only a single instance of a `Store` exists while the app is running.

Our examples do this by initializing `Store` in the apps main function, which should only ever get called once IIRC.

Feel free to share a code example if you think we can improve the behavior or our code examples of ObjectBox.

**Comment by venky9885** [comment]
i am also facing same issue in windows application making flutter in object box version 1.6.0

**Comment by venky9885** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: failed to create store: 10001 Cannot open store: another store is still open using the same path: "C:\Users\venky\Documents\objectbox"
#0      ObjectBoxNativeError.throwMapped (package:objectbox/src/native/bindings/helpers.dart:66)
#1      throwLatestNativeError (package:objectbox/src/native/bindings/helpers.dart:50)
#2      checkObxPtr (package:objectbox/src/native/bindings/helpers.dart:32)
#3      Store._checkStorePointer (package:objectbox/src/native/store.dart:309)
#4      new Store (package:objectbox/src/native/store.dart:150)
#5      openStore (package:soft_desk/objectbox.g.dart:180)
<asynchronous suspension>
#6      main (package:soft_desk/main.dart:97)
<asynchronous suspension>


These are the logs

**Comment by venky9885** [comment]
i tried changing versions from 1.2.0 to 1.6.0 But there is no use
i am making windows application using flutter

**Comment by greenrobot-team** [comment]
@venky9885 Are you sure the code that opens the store is only called once? You can [use `Store.isOpen(directory)`](https://pub.dev/documentation/objectbox/latest/objectbox/Store/isOpen.html) to add a simple check.
