### ISSUE TITLE
[Flutter] Add a method to check if a Store is already open on a given path

### ISSUE THREAD

**Issue by navaronbracke** [objectbox/objectbox-dart#435]
### Describe the solution you'd like

There should be a method that checks if a given `Store` is already open on a given path (using the default directory path as default), similar to `Store.isClosed()`.

### Describe alternatives you've considered

I've tried using a try catch block and checking for the `StateError` that is thrown.

### Additional context

I am using a Flutter app that uses ObjectBox as database and [workmanager](https://pub.dev/packages/workmanager).

I have several situations:
1) App is not running (void main(){} is not started) but WorkManager executes work using the Android API and the `_taskRunner()` entrypoint.
2) App is running and does not schedule WorkManager jobs
3) App is running and WorkManager runs tasks as well <- here I get 2 usages of the database at the same time

In case 3 I bump into `Bad state: failed to create store: 10001 Cannot open store: another store is still open using the same path`
I am currently evaluating if `Store.attach()` will work for case 3. Will report back if it worked or not.

Code sample:

main entry point of the app
```
import 'package:flutter/widgets.dart' show WidgetsFlutterBinding, runApp;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await DatabaseService().init(); // calls openStore() and stores a reference to it in a static singleton

  runApp(MaterialApp(...)); // Uses the database like a normal app, also queues work with WorkManager.
}
```

This is the entrypoint for WorkManager tasks that are run independent of the Flutter app. 
```
@pragma("vm:entry-point")
void _taskRunner() {
  WidgetsFlutterBinding.ensureInitialized();

  Workmanager().executeTask((taskName, inputData) async {
    await DatabaseService().initialize();

    switch (taskName) {
      case WorkManagerBackgroundTaskService._uploadStepTaskIdentifier:
        try {
          await doWork(databaseService);

          return true;
        } catch (error) {
          print(error);

          return false;
        } finally {
          DatabaseService().dispose();
        }
      default:
        return Future.error(
          ArgumentError.value(taskName, 'taskName', 'Unsupported task type.'),
        );
    }
  });
}
```

**Comment by greenrobot-team** [comment]
There is a static method [`Store.isOpen(directory)`](https://pub.dev/documentation/objectbox/latest/objectbox/Store/isOpen.html). Does that not work for your use case?

**Comment by navaronbracke** [comment]
@greenrobot-team The static method did the trick. Closing as working as intended.

**Comment by pratikPSB** [comment]
@navaronbracke How Have you solved this error?
I have also tried using this static method.
if possible then please give a reference code here.
I'm also doing the same kind of thing you did.

in the main.dart file I have this below code.

```dart
late ObjectBoxUtils objectBoxUtils;

@pragma('vm:entry-point')
void callbackDispatcher() async {
  WidgetsFlutterBinding.ensureInitialized();
  GeofenceForegroundService().handleTrigger(
    backgroundTriggerHandler: (zoneID, triggerType) async {
      Logger.doLog("zoneID : $zoneID, triggerType : $triggerType");
      if (triggerType == GeofenceEventType.enter) {
        if (!await ObjectBoxUtils.isStoreAlreadyOpen()) {
          await ObjectBoxUtils.create();
        }
        LocationAlarmModel? alarmModel = objectBoxUtils.getAlarmByFenceId(zoneID);
        // await handleAlarmCall(zoneID);
      } else if (triggerType == GeofenceEventType.exit) {
        Logger.doLog("zoneID : $zoneID, triggerType : exit");
      } else if (triggerType == GeofenceEventType.dwell) {
        Logger.doLog("zoneID : $zoneID, triggerType : dwell");
      } else {
        Logger.doLog("zoneID : $zoneID, triggerType : unknown");
      }
      return Future.value(true);
    },
  );
}

Future<void> main() async {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  //my other code
  objectBoxUtils = await ObjectBoxUtils.create();
  runApp(const MyApp());
}
```

In the ObjectBoxUtils class, I am checking whether the box is open by using the below method.
```dart
static isStoreAlreadyOpen() async {
    return Store.isOpen(join((await getApplicationDocumentsDirectory()).path, "gps-alarm"));
  }
```

error I'm facing is 
```log
E/GeofenceService(22006): errorCode: error, errorMessage: LateInitializationError: Field 'objectBoxUtils' has not been initialized.
```

**Comment by greenrobot-team** [comment]
@pratikPSB Your `callbackDispatcher` method does not initialize `objectBoxUtils`, as the error message says. This does not appear to be an ObjectBox specific issue.
