### ISSUE TITLE
ArgumentError (Invalid argument(s): Failed to lookup symbol 'obx_version_is_at_least': undefined symbol: obx_version_is_at_least)

### ISSUE THREAD

**Issue by JavonHuang** [objectbox/objectbox-dart#437]
:rotating_light: First, please check:

- existing issues,
- FAQs https://github.com/objectbox/objectbox-dart#faq

ArgumentError (Invalid argument(s): Failed to lookup symbol 'obx_version_is_at_least': undefined symbol: obx_version_is_at_least)

- ObjectBox version: [e.g. 0.14.0]
- Flutter/Dart SDK: [e.g. 2.0.0, or the output of `dart --version` or `flutter --version`]
- Null-safety enabled: [yes | no]
- Reproducibility: [e.g. occurred once only | occasionally without visible pattern | always]
- OS: [e.g. Linux 5.10.23 | Windows 10 | macOs BigSur | Android 10 | ... ]
- Device/Emulator: [e.g. Galaxy S20]

Additionally, you can choose to provide more details, e.g. the output of:

* `pub deps --no-dev`
* `flutter doctor -v`

### Steps to reproduce

1. Put '...'
2. Make changes to '....'
3. See error

### Code

If applicable, add code to help explain your problem.

- Include your pubspec.yaml.
- Include affected entity classes.
- Please remove any unnecessary or confidential parts.
- At best, link to or attach a project with a failing test.

### Logs, stack traces

If applicable, add relevant logs, or a stack trace.

### Additional context

- Is there anything special about your app?
- May transactions or multi-threading play a role?
- Did you find any workarounds to prevent the issue?

**Comment by greenrobot-team** [comment]
Is this #252? Then this is fixed with the new `1.6.0` release.

If not, please share what needs to be done to reproduce this.
