### ISSUE TITLE
10001 Cannot open store after exiting app by going back

### ISSUE THREAD

**Issue by greenrobot-team** [objectbox/objectbox-dart#442]
When exiting a Flutter app using the back navigation button, then re-launching it the following exception appears:

`10001 Cannot open store: another store is still open using the same path`

### Basic info (please complete the following information):

- ObjectBox version: 1.5.0
- Flutter/Dart SDK: 3.0.3
- Reproducibility: always
- OS: Android

Moved out of similar, but unrelated (Flutter hot restart) #387

**Comment by greenrobot-team** [comment]
@BLB-EN438 @animedev1 I can't reproduce this [with our example](https://github.com/objectbox/objectbox-dart/tree/main/objectbox/example/flutter/objectbox_demo_relations) (e.g. launch, press back, then launch the app from the launcher shortcut again).

Is ObjectBox in your project maybe set up differently from the example?

**Comment by techouse** [comment]
I have had the same error when opening a deep link on a Huawei Honor 10 running Android 10.

I have traced it down to that particular Android OS executing the deep link to my Flutter app within the parent app where the deep link came from, i.e. WhatsApp.

**Comment by greenrobot-team** [comment]
@techouse Thanks for the details! So this is another workaround instead of using an is open check and doing attach vs. open, see #436.

Then #436 is not an edge case after all and a Store being opened multiple times can actually happen more frequently than I thought. We maybe should add guidance in the docs about this then or maybe adapt our API if possible.

**Comment by user97116** [comment]
E/flutter (10735): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: failed to create transaction: Cannot start a write transaction inside a read only transaction (OBX_ERROR code 10001)
E/flutter (10735): #0      ObjectBoxNativeError.throwMapped (package:objectbox/src/native/bindings/helpers.dart:74:9)
E/flutter (10735): #1      throwLatestNativeError (package:objectbox/src/native/bindings/helpers.dart:54:48)
E/flutter (10735): #2      checkObxPtr (package:objectbox/src/native/bindings/helpers.dart:31:5)
E/flutter (10735): #3      new Transaction (package:objectbox/src/native/transaction.dart:33:5)
E/flutter (10735): #4      Store._runInTransaction (package:objectbox/src/native/store.dart:712:32)
E/flutter (10735): #5      InternalStoreAccess.runInTransaction (package:objectbox/src/native/store.dart:836:13)
E/flutter (10735): #6      Box.put (package:objectbox/src/native/box.dart:94:34)
E/flutter (10735): #7      TaskObjectBoxApi.addUpdate (package:progress/data/objectbox/apis/task_api.dart:15:44)
E/flutter (10735): #8      UnplannedApi.onAdd (package:progress/migrate/domain/unplanned_api.dart:79:22)
E/flutter (10735): #9      _AddUpdateUnplannedSubtaskPageState.onAdd (package:progress/migrate/views/unplanned/add_subtask/add_subtask_page.dart:178:10)
E/flutter (10735): #10     _AddUpdateUnplannedSubtaskPageState.build.<anonymous closure> (package:progress/migrate/views/unplanned/add_subtask/add_subtask_page.dart:152:31)
E/flutter (10735): <asynchronous suspension>
E/flutter (10735):
D/ColorViewRootUtil(10735): nav bar mode ignore false downX 191 downY 609 mScreenHeight 2340 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=191.0, y[0]=609.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=70454557, downTime=70454557, deviceId=6, source=0x1002, displayId=0 }
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
D/ColorViewRootUtil(10735): nav bar mode ignore false downX 113 downY 185 mScreenHeight 2340 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=113.0, y[0]=185.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=70455241, downTime=70455241, deviceId=6, source=0x1002, displayId=0 }
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
I/chatty  (10735): uid=12708(amar.progress) identical 8 lines
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
I/TRuntime.CctTransportBackend(10735): Making request to: https://firebaselogging.googleapis.com/v0cc/log/batch?format=json_proto3
I/TRuntime.CctTransportBackend(10735): Status Code: 200
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
I/chatty  (10735): uid=12708(amar.progress) identical 5 lines
E/UIFirst (10735): failed to open /proc/10735/stuck_info, No such file or directory
