### ISSUE TITLE
 Request to update generator analyser to analyser ^4.x

### ISSUE THREAD

**Issue by eEQK** [objectbox/objectbox-dart#443]
similarly to https://github.com/objectbox/objectbox-dart/issues/380

The newest version of `freezed` clashes with `objectbox` due to `analyser` API changes introduced in version 4.1.0 of analyser

**Comment by greenrobot-team** [comment]
The next release should allow analyzer v4 versions.

**Comment by greenrobot-team** [comment]
Now available with the `1.6.1` release.
