### ISSUE TITLE
Set objectbox.g.dart generated file to be ignored by flutter coverage

### ISSUE THREAD

**Issue by Brunobnahorny** [objectbox/objectbox-dart#444]
For a realistic test coverage result. Dart coverage should be able to ignore a file. Unfortunaly there is no easy tool use for this.

I know this should be the role of source_gen instead, not Objectbox, as this isn't Objectbox-specific. But i guess until source_gen provides the solution to the issue, this would a great solution.

A simple `// coverage:ignore-file` line under the actual `// ignore_for_file: camel_case_types` should resolve the issue

**Comment by greenrobot-team** [comment]
Thanks for reporting and creating a PR! Could you share how you run the coverage tool so we can repro? It's fine to link to docs if you followed them exactly.

**Comment by Brunobnahorny** [comment]
Sure.
I created a full working minimal example in [here](https://github.com/Brunobnahorny/objectbox_coverage_example). It's not that simple to reproduce since to show, in Lcov.info flutter's generated file, the tests needs pass into generated objectbox.g.dart.

I didn't include objectbox native drivers for safety.

Documentation used: 
https://docs.objectbox.io/getting-started
https://pub.dev/packages/test#collecting-code-coverage

**Comment by greenrobot-team** [comment]
Thanks again! Could verify this works as expected. Your fix should ship with the next release.

Note: the current workaround is to remove the `objectbox.g.dart` file from the generated `lcov.info` file. E.g. using
`lcov --remove coverage/lcov.info 'lib/objectbox.g.dart' -o coverage/lcov.info`
