### ISSUE TITLE
[Windows] Changes are only visible after a full/hot restart of the app

### ISSUE THREAD

**Issue by dr0-dev** [objectbox/objectbox-dart#452]
I downloaded the basic example and it happens on that too. 

https://user-images.githubusercontent.com/70333416/183419423-44c2637c-6bf9-4303-bb06-482e02eb7a02.mov

Only if I restart the app (or Hot reload it) the new values are visible.

In another use case I found that deleting an item and then listing all the items straight after, still gives me the deleted item. If I close/restart the app, the item results actually deleted.

This happens on windows only. Flutter 2.10.5

**Comment by greenrobot-team** [comment]
Works fine for me on Windows 10 and Flutter 3.0.5 with https://github.com/objectbox/objectbox-dart/tree/main/objectbox/example/flutter/objectbox_demo.

Where did you download the example app from?

**Comment by dr0-dev** [comment]
I cloned the repo that you linked above and ran it. This is Windows 11, not sure if that makes a difference. I will try to run it with Flutter 3.x
