### ISSUE TITLE
When you open and close the store several times in a row, the app is crashing constantly

### ISSUE THREAD

**Issue by eli1stark** [objectbox/objectbox-dart#454]
I have 2 flutter apps and I share a database between them using the IOS app groups container, my 2 flutter apps can run simultaneously on the same device and when I add an entity on app A and then go to app B, the newly added entity is displayed in app B. So, there are 2 apps and 2 stores that are open and contribute to the same database. When I add an entity in app A and then go to app B and try to add something there, it updates the entity which I added in app A instead of adding a new entity. I think this happens because 2 stores keep track of ids internally and they don't rely on database source, so, when I have the latest id of 7 and add a new entity with the id of 8, in the app where I added everything is alright since the store has the latest id, but when I go to another app there is still id of 7 and when I put new entity it puts it with the id of 8 and since id of 8 exists already, instead of creating a new entity with the id of 9, it updates the entity with the id of 8.

In order to fix this issue, I came up with a workaround. Every time a user switch between apps I close the old store and open a new store, this allows the new store to fetch the latest id from the database source. But I noticed when I do a lot of switches back and forth like 2 or 3, the emulator is crashing without an error and it's pretty much constant behavior, you just need to do enough of closing and opening in order to cause a crash of the app.

So, my questions are, is this a bug, and how to fix it, what workarounds do you have? 
My primary goal is to share the database between 2 flutter apps in the runtime. `Store.attach()` won't help here since they are running in separate Dart VMs.

I'm using the latest version of objectbox (1.6.0) and flutter 3.0.5

**Comment by eli1stark** [comment]
And this can be somehow similar to this [issue](https://github.com/objectbox/objectbox-dart/issues/385), the only difference here is I don't have an error and I'm not trying to swap data.mdb, I just work with the same database from 2 flutter apps using a separate store in each of them.

**Comment by eli1stark** [comment]
I started to use self-assignable ids and this allows me to not close stores and have them open, so crash related to close-open is kind of resolved. But when 2 apps are in production, they crash on the first switch. When I go from App A to App B, App A is crashed. I don't close and reopen stores, I just switch from one app to another.

**Comment by greenrobot-team** [comment]
ObjectBox does not support accessing the same database file in read/write mode from two different processes, like in this case two separate apps. It would be possible to open one database in write mode and one or more others in read-only mode. However, read-only mode is only supported in our Java library at the moment.

Technically, it should be possible to close a store and then open it someplace else (assuming the model is the same). But that requires careful synchronization/locking to avoid concurrent access from different processes.

My recommendation is to not use shared files at all. Instead let each app have its own database in it's isolated app directory. Then provide some API for inter-process communication (on device, or via a third-party like a web server) to share anything that needs to be shared.
