### ISSUE TITLE
After Android saves the data, an error is reported when running again, and there will be a flash back when I debug the breakpoint

### ISSUE THREAD

**Issue by Aaron009** [objectbox/objectbox-dart#459]
The error screenshot is as follows：
<img width="783" alt="image" src="https://user-images.githubusercontent.com/3838050/186075938-cc588fcd-0559-4faf-8ac8-770d25814731.png">

<img width="603" alt="image" src="https://user-images.githubusercontent.com/3838050/186076084-c8655e26-b388-4c41-b081-512cc3a27805.png">

**Comment by greenrobot-team** [comment]
Thanks! Can you please share additional details (code snippets, what versions you are using, instructions) that allow us to reproduce this problem?

**Comment by Aaron009** [comment]
@

> code snippets
this example :
https://github.com/Aaron009/bug_objectbox

Android, the second time you open it, it will report an error.

**Comment by greenrobot-team** [comment]
If I read the code correctly, it may call `openStore()` multiple times. Try to call `initDataBase()` from the `main` method of your app instead. Like in our examples: https://github.com/objectbox/objectbox-dart/blob/6c2176dd7e0872c21e90d2e90d7cc0a7b63053c9/objectbox/example/flutter/objectbox_demo_relations/lib/main.dart#L12-L20

**Comment by Aaron009** [comment]
> If I read the code correctly, it may call `openStore()` multiple times. Try to call `initDataBase()` from the `main` method of your app instead. Like in our examples:
> 
> https://github.com/objectbox/objectbox-dart/blob/6c2176dd7e0872c21e90d2e90d7cc0a7b63053c9/objectbox/example/flutter/objectbox_demo_relations/lib/main.dart#L12-L20

I'm pretty sure it's only called once.
I've hit print log and also found that it's only called once.

```shell
I/flutter (18852): initDataBase initDataBase!
I/flutter (18852): getBox getBox!
E/flutter (18852): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: RangeError (byteOffset): Invalid value: Valid value range is empty: 0
E/flutter (18852): #0      ObjectCollectorError.throwIfError (package:objectbox/src/native/bindings/data_visitor.dart:58:24)
E/flutter (18852): #1      Query.find (package:objectbox/src/native/query/query.dart:827:18)
E/flutter (18852): #2      DataBase.getLanguageData (package:bug/main.dart:196:25)
E/flutter (18852): #3      _MyHomePageState.initDataBase (package:bug/main.dart:79:35)
E/flutter (18852): <asynchronous suspension>
```

**Comment by greenrobot-team** [comment]
`E/flutter (18852): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: RangeError (byteOffset): Invalid value: Valid value range is empty: 0`

This is #460, a fix is available with the latest release: https://github.com/objectbox/objectbox-dart/releases/tag/v1.6.2
