### ISSUE TITLE
[feature] lint warnings for redundant queries

### ISSUE THREAD

**Issue by navaronbracke** [objectbox/objectbox-dart#467]
I wrote a query to find an Entity which actually had a bit of unnecessary code in it.

I.e.

```
@Entity
class Foo {
  Foo({
   this.localId = 0,
  });

  @Id()
  int localId;
}

final condition = Foo_.localId.isNotNull() & Foo_.localId.equals(42);
```

Because `localId` is an int and the default value is 0, this value can never be null.
Thus the `Foo_.localId.isNotNull()` check is redundant.

### Describe the solution you'd like

I'd like to see lint warnings for query code that does not make sense.
Not sure where those can be applied though. (apart from the above example)

For the above example what if the `isNotNull()` function could show a lint warning, or be removed for non-null fields?
Although the latter might break things.

### Describe alternatives you've considered

Using analysis_options.yml to configure lints does not really help since the code uses binary operations on integers.

### Additional context

N/A

**Comment by greenrobot-team** [comment]
Thanks for the suggestion!

However, I don't think this is something that can be solved by static analysis. E.g. it is possible to add a new property. Then all existing objects will have a null value for that. Or when using Sync a null value might be brought in from the server.

So there are valid use cases to use a `isNotNull()` condition on database data even though in the Dart binding the field is never null. I guess the important thing is to remember that the ObjectBox Dart API is just a wrapper around the ObjectBox (cross-platform) database model.

**Comment by navaronbracke** [comment]
Thanks for the reply.

I do agree that if it is not something that can be caught using static analysis, then there is nothing we can really do here.
I just wanted to bring it up and get a second opinion on it.
