### ISSUE TITLE
Changed Box Property Type and OpenStore now broken

### ISSUE THREAD

**Issue by arkeri** [objectbox/objectbox-dart#470]
I couldn't find anything helpful in the StackOverflow or FAQs about this. 

### Basic info (please complete the following information):

- ObjectBox version:1.6.0
- Flutter/Dart SDK: 3.0.5
- Null-safety enabled: [yes]
- Reproducibility: Have objects stored in ToMany<OtherBox> and convert to String type instead
- Device/Emulator: iPhone 12

1. Create a box with property of type ToMany<OtherBox> and add data into model
2. Change type of property from ToMany<OtherBox>  to string and regenerate mobel
3. Run app and see openStore causing crash of unhandled error

### Expected behavior

I would expect this to throw an error that I could handle i.e. generating the store and throwing an error on touching one of the boxes. That why I can dynamically clear the box or run some logic to restore a functioning state across versions of the app without having to have people delete the app entirely and redownload it for it to function. 

### Code

```
class ObjectBox {
  /// The Store of this app.
  late final Store store;

  /// Set up boxes.
  late final Box<UserBox> userBox;
  late final Box<AttributeBox> attributeBox;
  late final Box<LocationBox> locationBox;

  ObjectBox._create(this.store) {
    ///Initialize the Boxes
    locationBox = Box<LocationBox>(store);
    attributeBox = Box<AttributeBox>(store);
    userBox = Box<UserBox>(store);
  }

  /// Create an instance of ObjectBox to use throughout the app.
  static Future<ObjectBox> create() async {
    try {
     final store = await openStore();
    } on ObjectBoxException {
      
    }
    final store = await openStore();

    return ObjectBox._create(store);
  }

  Future<void> clearAll() async {
    Future.wait([
      _clear(locationBox),
      _clear(attributeBox),

    ]);
  }
}

Future<int> _clear(Box box) async {
  return await box.removeAll();
}
```

```
@Entity(uid: 1)
class LocationBox {
  @Id(assignable: true)
  int id;
  String name;
  // ToMany<AttributeBox> attributes;
  String attributes;

  LocationBox({
    required this.id,
    required this.name,
    required this.attributes,
  });
}

```

 objectbox: ^1.6.0
 objectbox_flutter_libs: any

### Logs, stack traces

```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: ObjectBoxException: failed to create store: 10199 Remove failed (-30788)
#0      ObjectBoxNativeError.throwMapped
package:objectbox/…/bindings/helpers.dart:78
#1      throwLatestNativeError
package:objectbox/…/bindings/helpers.dart:50
#2      checkObxPtr
package:objectbox/…/bindings/helpers.dart:32
#3      Store._checkStorePointer
package:objectbox/…/native/store.dart:367
#4      new Store
package:objectbox/…/native/store.dart:208
#5      openStore
package:adventurer_app/objectbox.g.dart:580
<asynchronous suspension>
#6      ObjectBox.create
package:adventurer_app/…/core/objectbox.dart:49
<asynchronous suspension>
#7      main
package:adventurer_app/main.dart:72
<asynchronous suspension>
```

**Comment by Vahid1919** [comment]
ObjectBox manages data models mostly automatically, but if you rename/change the datatype of a property you have to take a few additional steps in order to clear up any ambiguity. See https://docs.objectbox.io/advanced/data-model-updates and let me know if that fixes your issue.

**Comment by arkeri** [comment]
I'm looking in to see if that would work for us but not it's telling me that all our UIDs changed can that it's requiring I define a new uid @Property for every single objectbox object, including the IDs, and I can't have two annotations in a row so I can't do @ID or @Index with a new UID from @Property.

**Comment by Vahid1919** [comment]
You only need to add a @uid annotation on the properties you have changed.
