### ISSUE TITLE
Analyzer dependency is outdated

### ISSUE THREAD

**Issue by mgesmundo** [objectbox/objectbox-dart#487]
The Analyzer dependency is < 5.0.0, but other packages requires at least > 5.0.0.
Thank you

**Comment by greenrobot-team** [comment]
Thanks for reporting! We typically update third party dependencies, like analyzer, with every release.

Anyhow, are you sure that these packages require analyzer v5? And what packages are we talking about? Note that you might be able to use an older version of these packages in the meantime.

**Comment by mgesmundo** [comment]
Thank you @greenrobot-team,
the package that requires analyzer > 5.0 is `envied_generator`.
Of course for now I override the dependency.

**Comment by haaris94** [comment]
Freezed also requires analyzer > 5.0

**Comment by greenrobot-team** [comment]
@mgesmundo @haaris94 Out of curiosity, how are you updating your dependencies? E.g. `dart pub upgrade` or `flutter pub upgrade` should make sure that your package does not use a version of another package that is incompatible,

**Comment by greenrobot-team** [comment]
`1.7.0` is out which allows analyzer v5.
