### ISSUE TITLE
Support for modular approach - using multiple database definition files

### ISSUE THREAD

**Issue by Chris1234567899** [objectbox/objectbox-dart#488]
It would be awesome for object box to support modular designed apps.

I give you an example:
I have a shared (local) package that contains base models, shared services etc and has it's own package pubspec.yaml file. Inside this module, I make heavily use of objectbox storage so I generate the according objectbox-model.json and objectbox.g.dart files.

Then I have 1-n mobile applications that import this shared package, but additionally bring their own models and therefore generate their own objectbox-model.json and objectbox.g.dart file.

Problem is, apparently objectbox just uses one database definition file and therefore it results in errors that entity xy does not exist (because it's obviously in the other db definition file).

### Describe the solution you'd like

It would be awesome if we could add multiple database definitions with their paths as a list when instantiating objectbox. Or maybe join them or something.

**Comment by greenrobot-team** [comment]
Thanks for the request. See my answer at https://github.com/objectbox/objectbox-dart/issues/466#issuecomment-1237698759.
