### ISSUE TITLE
Async/Await/Futures

### ISSUE THREAD

**Issue by vaind** [objectbox/objectbox-dart#49]
Looking at some other dart code I've got an impression the API should be asynchronous (returning Futures). Thoughts?

**Comment by Buggaboo** [comment]
This was [mentioned before here](https://github.com/objectbox/objectbox-dart/issues/5#issuecomment-539603684).

I was thinking of starting on this, after we've tackled other high-priority issues.

**Comment by vaind** [comment]
The comment mentioned C async ops, which are only a part of the picture, and I'm not sure they can be used now with futures because there's currently no way to tell if the operation has finished.

The main goal I had in mind with raising this issue question was first to discuss whether it makes sense to change the standard Box APIs, like get, put, delete, etc to returning `Future`s.

**Comment by Buggaboo** [comment]
> The comment mentioned C async ops, which are only a part of the picture, and I'm not sure they can be used now with futures because there's currently no way to tell if the operation has finished.
> 
> The main goal I had in mind with raising this issue question was first to discuss whether it makes sense to change the standard Box APIs, like get, put, delete, etc to returning `Future`s.

How about the observer ops? Could those help?

**Comment by softkot** [comment]
Async methods like find() is a highly required feature.
