### ISSUE TITLE
Request for QueryFilters as implemented for Java and Kotlin

### ISSUE THREAD

**Issue by MBjoern** [objectbox/objectbox-dart#490]
I'd love to see the QueryFilters also being available for dart to really improve the possibility to query the data properly.

QueryFilter for Java/Kotlin
https://docs.objectbox.io/queries#query-filters

Is there any timeline for this feature in dart?

**Comment by greenrobot-team** [comment]
Thanks for the request. However, we never considered adding this as Dart already has a powerful filtering API. E.g. use `.where()` on the result list. Is there any reason why you would not want to use that in your code?
