### ISSUE TITLE
Unable to create new Object Box Database in flutter dart

### ISSUE THREAD

**Issue by jkrogers9862** [objectbox/objectbox-dart#509]
I am seeing an issue but it is with a brand new branch and database, the nuke option from the docs above does not even work either. I had no previous versions of a database and I was just investigating using ObjectBox so I am not sure if it is my entity that are wrong or what but I am providing what configuration I am using.

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ObjectBoxException: failed to create store: Incoming entity ID 1:1159196401019035950 does not match existing UID 19695048053676317
#0      ObjectBoxNativeError.throwMapped (package:objectbox/src/native/bindings/helpers.dart:84:9)
#1      throwLatestNativeError (package:objectbox/src/native/bindings/helpers.dart:50:48)
#2      checkObxPtr (package:objectbox/src/native/bindings/helpers.dart:32:5)
#3      Store._checkStorePointer (package:objectbox/src/native/store.dart:370:7)
#4      new Store (package:objectbox/src/native/store.dart:211:7)
#5      openStore (package:my_app/db/gen/objectbox.g.dart:103:5)
#6      ObjectRepository._create (package:my_app/db/object_repository.dart:38:25)
<asynchronous suspension>

Lost connection to device.

pubspec.yaml: 
dependencies:
  objectbox: ^1.7.2
  objectbox_sync_flutter_libs: any

  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  objectbox_generator: any

objectbox:
  output_dir: db/gen

[writer_entity.dart.txt](https://github.com/objectbox/objectbox-dart/files/10715981/writer_entity.dart.txt)

**Comment by jkrogers9862** [comment]
Not an issue, User error.

**Comment by Djostanisic** [comment]
I have the same issue, can you explain please what was the user error, what caused this problem?

**Comment by greenrobot-team** [comment]
@Djostanisic This error is explained at https://docs.objectbox.io/troubleshooting#dbschemaexception-incoming-id-does-not-match-existing-uid

**Comment by jkrogers9862** [comment]
My recommendation is to version control your test databases in a separate for each branch you work with. I don't honestly remember what I did to fix it but I know I haven't seen it since I started doing this. 

I am actually look to switch to isar because as of right now, objectbox does not support web which I want to expand to.
