### ISSUE TITLE
ObjectBrowser / Admin on iOS

### ISSUE THREAD

**Issue by leononly** [objectbox/objectbox-dart#521]
Was wondering, is this feature is in the plan? it would be very helpful if this feature is available for iOS users, we want to include this feature in our app so that we can access the db on the client side by just view the db data on the device

**Comment by greenrobot-team** [comment]
Thanks for the request! Currently Admin works for Android apps only and there are no immediate plans to make it work on iOS or macOS.

For anyone else interested, please thumbs up the first post so we can track interest in this!

**Comment by greenrobot-team** [comment]
We have released Admin as a Docker image, that can be used to read a database file on your development machine. See https://docs.objectbox.io/data-browser#run-via-docker for details.
