### ISSUE TITLE
@Index doesn't work for getter/setter properties

### ISSUE THREAD

**Issue by 23doors** [objectbox/objectbox-dart#528]
### Basic info (please complete the following information):

- ObjectBox version: 2.0.0
- Flutter/Dart SDK: [e.g. 2.0.0, or the output of `dart --version` or `flutter --version`]
- Null-safety enabled: yes
- Reproducibility: always

### Steps to reproduce

Entity with:
```
  @Transient()
  DateTime? utcDate;

  @Index()
  int get dbUtcDate => utcDate?.millisecondsSinceEpoch ?? 0;

  set dbUtcDate(int value) {
    utcDate = DateTime.fromMillisecondsSinceEpoch(value, isUtc: true);
  }
```

generates objectbox-model.json without index:
```
        {
          "id": "46:2219823090073850885",
          "name": "dbUtcDate",
          "type": 6
        }
```

### Expected behavior

Above should generate indexed property, just like this does (version without transient + getter/setter):
```
  @Index()
  int? dbUtcDate;
```

generates:
```
        {
          "id": "46:2219823090073850885",
          "name": "dbUtcDate",
          "type": 6,
          "flags": 8,
          "indexId": "35:4553977394910343818"
        }
```

**Comment by greenrobot-team** [comment]
Thanks for reporting! Merging this with #392 (and closing this).
