### ISSUE TITLE
Error during opening of ObjectBox-Dart library on the macOS

### ISSUE THREAD

**Issue by ksatalsin** [objectbox/objectbox-dart#535]
- existing issues : [simmilar](https://github.com/objectbox/objectbox-dart/issues/248)

When attempting to initialize the ObjectBox-Dart library without specifying a folder, an error occurs with an "Operation not permitted" (code 1) message.  This is happening with the sandbox = ON in the entitlement runner file. The step with groups was done as described https://swift.objectbox.io/advanced/macos

- ObjectBox version: 2.0.0
- Flutter/Dart SDK: Flutter 3.7.12
- Null-safety enabled: y
- Reproducibility:  always
- OS: macOS any
- Device/Emulator: 

### Steps to reproduce

1. Add the ObjectBox-Dart library.
2. Set sandbox mode to ON in the entitlements file by adding the following code:

```
<key>com.apple.security.app-sandbox</key>
<true/>
```
3. Attempt to open the ObjectBox-Dart library without specifying a folder in the code, like this:

` final store = await openStore();`

### Expected behavior
Should be able to proceed without exception, because I am able to read/write data in the same folder

**Comment by greenrobot-team** [comment]
The docs you linked are for objectbox-swift. For Flutter you also need to pass the application group to Store, see the [info box "For sandboxed macOS apps"](https://docs.objectbox.io/getting-started#:~:text=For%20sandboxed%20macOS%20apps).

**Comment by greenrobot-team** [comment]
[Quoting the docs](https://docs.objectbox.io/getting-started#:~:text=there%27s%20an%20internal%20limit%20in%20macOS%20that%20requires%20the%20complete%20string%20to%20be%2019%20characters%20or%20fewer.):
> there's an internal limit in macOS that requires the complete string to be 19 characters or fewer.

**Comment by DzianisMatveyeu** [comment]
> [Quoting the docs](https://docs.objectbox.io/getting-started#:~:text=there%27s%20an%20internal%20limit%20in%20macOS%20that%20requires%20the%20complete%20string%20to%20be%2019%20characters%20or%20fewer.):
> 
> > Note: Pick a short group identifier; there's an internal limit in macOS that requires the complete string to be 19 characters or fewer.

full string( $(TeamIdentifierPrefix).$(BundleId)) should be shorter or only the group id? If it first, shud I change my bundle id to shorter version?
If I use $(TeamIdentifierPrefix) as the group id, I also get a black screen.
```
<key>com.apple.security.application-groups</key>
<array>
<string>$(TeamIdentifierPrefix)</string>
```

**Comment by greenrobot-team** [comment]
@DzianisMatveyeu The 19 character limit is for the whole string passed to `openStore(macosApplicationGroup: 'FGDTDLOBXDJ.demo')`. E.g. in this example `FGDTDLOBXDJ.demo`.

**Comment by DzianisMatveyeu** [comment]
I have 18 characters on macosApplicationGroup, but I still get this error
![изображение](https://github.com/objectbox/objectbox-dart/assets/105710544/2a0a5795-c630-4c33-a38f-61a328b12d65)
