### ISSUE TITLE
[Flutter] ObjectBox Admin web app is not working 

### ISSUE THREAD

**Issue by luanmvieira** [objectbox/objectbox-dart#541]
I/Box     ( 6534): [SvHttp] Running in single-store mode with an already opened store
I/Box     ( 6534): [SvHttp] Listening on http://127.0.0.1:8090
I/Box     ( 6534): [SvHttp] User management: disabled
I/Box     ( 6534): [SvHttp] HttpServer listening on 127.0.0.1, port 8090

Admin web app is not working when opening URL
http://127.0.0.1:8090/

- ObjectBox version: [2.0.0]
- Dart SDK version: 2.19.4
- Flutter 3.7.7
- Reproducible: [always]
- Build OS: [Windows 10]
- Deployment device or OS: [Emulator in API 32 and 31 ]

Log

![image](https://github.com/objectbox/objectbox-dart/assets/81385730/9cdf14bf-2450-4077-94ac-cf5d47c05696)

Gradle

![image](https://github.com/objectbox/objectbox-dart/assets/81385730/9e19e56a-abca-4f14-b3f0-0ed3da883821)

Manifest 

![image](https://github.com/objectbox/objectbox-dart/assets/81385730/318d7b37-b166-40cd-b5a6-34621d25c7f4)

Initialize

![image](https://github.com/objectbox/objectbox-dart/assets/81385730/e5420d3a-3946-4abc-965b-93695bb7a8e0)

App Browser

![image](https://github.com/objectbox/objectbox-dart/assets/81385730/75e91f11-2f64-474c-9b96-2c6791427a5f)

Web Browser in PC

![image](https://github.com/objectbox/objectbox-dart/assets/81385730/0abc5af1-d836-4818-8060-8ccfe9b35301)

I used "adb forward tcp:8090 tcp:8090" but it still doesn't work. what can I do?

**Comment by greenrobot-team** [comment]
Thanks for reporting. I tried using Admin with our example and it works as expected.

Is it possible that your app has been closed while trying to open Admin? Also check that the `Admin` instance does not get garbage collected.

In any case, maybe double-check you followed the instructions exactly [as documented](https://docs.objectbox.io/data-browser).

**Comment by luanmvieira** [comment]
I was able to identify the error, the way the store is implemented it keeps restarting with each store call, I solved the problem. Thank you very much!
