### ISSUE TITLE
Optional logging for streaming queries

### ISSUE THREAD

**Issue by 2x2xplz** [objectbox/objectbox-dart#543]
Requesting log settings that would notify of every execution of an ObjectBox query, especially by `watch`ed queries.

I've been experimenting with numerous reactive/streaming queries in ObjectBox, consumed by Riverpod providers. A number of these are dependent on each other, i.e. one provider's streamed queries are triggered by a change in the results of another streamed query. Because there's so much happening under the hood, I'd like to ensure that OB is only executing queries when necessary. 

### Describe the solution you'd like

During dev builds, I'd like to specify a log level that would trigger on every executed query. Thanks.

### Describe alternatives you've considered

Logging within the Riverpod providers but they only record when a new provider (which includes a new OB streamed query) is created, but not upon each execution of a query.

### Additional context

My concern is that some streamed queries may be executing far more often than necessary, for example every time a certain object is `put`, rather than just being triggered when the `put` changes a specific property.

**Comment by greenrobot-team** [comment]
> for example every time a certain object is put, rather than just being triggered when the put changes a specific property.

Maybe to clear that up: [as documented](https://pub.dev/documentation/objectbox/latest/objectbox/QueryBuilder/watch.html) an event is sent when any of the boxes that are part of the query updates. There are no object-specific or even property-specific events.

I don't know how your implementation looks like, but as for logging, maybe add log statements to the `map` or `listen` callbacks?
