### ISSUE TITLE
Could not find io.objectbox:objectbox-android-objectbrowser:2.2.1

### ISSUE THREAD

**Issue by FlippedOvO** [objectbox/objectbox-dart#554]
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    debugImplementation("io.objectbox:objectbox-android-objectbrowser:2.2.1")
}

got error 

   > Could not find io.objectbox:objectbox-android-objectbrowser:2.2.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/objectbox/objectbox-android-objectbrowser/2.2.1/objectbox-android-objectbrowser-2.2.1.pom
       - https://repo.maven.apache.org/maven2/io/objectbox/objectbox-android-objectbrowser/2.2.1/objectbox-android-objectbrowser-2.2.1.pom
       - https://storage.googleapis.com/download.flutter.io/io/objectbox/objectbox-android-objectbrowser/2.2.1/objectbox-android-objectbrowser-2.2.1.pom
       - https://jitpack.io/io/objectbox/objectbox-android-objectbrowser/2.2.1/objectbox-android-objectbrowser-2.2.1.pom
       - https://jcenter.bintray.com/io/objectbox/objectbox-android-objectbrowser/2.2.1/objectbox-android-objectbrowser-2.2.1.pom
     Required by:
         project :app

**Comment by greenrobot-team** [comment]
The `objectbox-android-objectbrowser` is versioned differently from the Dart library.

Try using version `3.5.1` that is included with [the `2.2.1` Dart library](https://github.com/objectbox/objectbox-dart/releases/tag/v2.2.1).

I also modified the release notes to mention the included version.
