### ISSUE TITLE
ObjectBox 0.18.1 problem archlinux desktop programming

### ISSUE THREAD

**Issue by trapthor** [objectbox/objectbox-dart#567]
archLinux still offers versions 0.18.0.1 with which ObjectBox 2.3.1 does not work when making Linux desktop programs. Version 2.2.0 works, so I'm using that version for now.
It would always be good to check that archLinux supports these reforms, because quite a lot of programmers use it or operating systems based on it.

**Comment by greenrobot-team** [comment]
To build and run a Flutter app for Linux desktop there is no need to install the ObjectBox shared library separately?

If you talk about Dart CLI apps, we recommend shipping the library with the executable. You can get a compatible version using the install.sh script in the repo for a given release tag.

If this doesn't apply, please share more about your use case!
