### ISSUE TITLE
Generated code contains multiple linting issues

### ISSUE THREAD

**Issue by JaffaKetchup** [objectbox/objectbox-dart#577]
### Is there an existing issue?

- [x] I have searched [existing issues](https://github.com/objectbox/objectbox-dart/issues)

### Build info

- objectbox version: 2.3.1
- Flutter/Dart version: 3.13.9 + 3.1.5
- Build OS: Windows 11
- Deployment OS or device: Windows 11 (but happens regardless of platforms)

### Steps to reproduce

1. Generate code from any model
2. Enable and observe the following lint issues:
   * [avoid_js_rounded_ints](https://dart.dev/tools/linter-rules/avoid_js_rounded_ints)
   * [cascade_invocations](https://dart.dev/tools/linter-rules/cascade_invocations)
   * [require_trailing_commas](https://dart.dev/tools/linter-rules/require_trailing_commas)

If needed, this is the file of lints I'm using: https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/42eed0e0d7f408665c2e4eeaa26cd3c4c51896ee/jaffa_lints.yaml

### Expected behavior

Either:
 * Add the lints above to the 'ignore_for_file' lints line
 * Actually fix the issues in generation

### Code

<details><summary>Code</summary>

```dart
@Entity()
class Foo {
  @Id()
  int id = 0;
}
```

</details>

**Comment by JaffaKetchup** [comment]
Thanks for the response!
I suppose you are right that I should exclude the file myself (I have done), I kinda forgot that :D

I appreciate you don't support the web platform, but the issue is that this could cause a poor pub score and/or cause ci issues. So I still think that 'avoid_js_rounded_ints' needs fixing. That was the original issue anyway :D

**Comment by JaffaKetchup** [comment]
Also, perhaps adding to the docs to exclude the file completely anyway might be worthwhile.

**Comment by greenrobot-team** [comment]
OK, this is a non-issue then. Closing.
