### ISSUE TITLE
Missing tests examples for Flutter/Dart

### ISSUE THREAD

**Issue by daniloapr** [objectbox/objectbox-dart#585]
### Is there an existing issue?

- [x] I have searched [existing issues](https://github.com/objectbox/objectbox-dart/issues)

### Use case

I would like to set up ObjectBox database for tests but couldn't find any examples in the docs or in the Github repository. Is there a way to test it?

### Proposed solution

1. Be able to setup test files like it's possible with other libraries such as [Isar](https://pub.dev/packages/isar#unit-tests) or [SharedPreferences](https://pub.dev/packages/shared_preferences#testing)
2. Add test examples in the official documentation and/or github repo examples.

Example for Isar:
```dart
Future<void> setUpIsarForTests() async {
  final binaryName = Platform.isWindows
      ? 'isar.dll'
      : Platform.isMacOS
          ? 'libisar.dylib'
          : 'libisar.so';

  final path = File('temp/$binaryName').absolute.path;

  await Isar.initializeIsarCore(
    download: true,
    libraries: {
      Abi.macosX64: path,
      Abi.macosArm64: path,
      Abi.linuxArm64: path,
      Abi.linuxX64: path,
      Abi.windowsX64: path,
    },
  );
}
```

### Describe alternatives you've considered

- Create a temporary directory for the database, but couldn't make ObjectBox use it

**Comment by greenrobot-team** [comment]
We have not looked at unit testing in a Flutter package for a while, maybe we should.

But if you are fine with a Dart only test package, see the one in this repo for inspiration: https://github.com/objectbox/objectbox-dart/tree/main/objectbox_test

[The add to project docs](https://docs.objectbox.io/getting-started) also have notes on how to download the C library required to run unit tests on your development machine.

Does that work for you?

**Comment by daniloapr** [comment]
Thanks for the response! Can you elaborate more on that?

What I need is to test a file in my Flutter project, which uses Object Box for data persisting, so I can ensure I'm performing the CRUD operations and complex queries properly. Would that work like that?
