### ISSUE TITLE
`build_runner build` should not touch examples

### ISSUE THREAD

**Issue by vaind** [objectbox/objectbox-dart#59]
Currently, when one runs `pub run build_runner build` in the library root, it also generates the code for examples, considering all files the same project, effectively combining their databases. How can we prevent that?

**Comment by liquidiert** [comment]
Probably this:
> Each target may also contain the following keys:  
> - sources: List of Strings or Map, Optional. The set of files within the package which make up this target. Files are specified using glob syntax. If a List of Strings is used they are considered the 'include' globs. If a Map is used can only have the keys `include` and `exclude`. Any file which matches any glob in `include` and no globs in `exclude` is considered a source of the target. When `include` is omitted every file is considered a match.

from [build_runner config](https://pub.dev/packages/build_config) helps :D

**Comment by vaind** [comment]
Implemented: 2d99df10b672505bb68eb2ec11a8a206a0eeaebc
