### ISSUE TITLE
generator error with retrofit

### ISSUE THREAD

**Issue by PrzemyslawPluszowy** [objectbox/objectbox-dart#593]
hello, can you explain me how to fix problem, im beginer in flutter. I have in pubspec jsonserializable and retrofit, and have problem with generation code in object box. For most project i use isar but i d'like try onjectbox

_Originally posted by @PrzemyslawPluszowy in https://github.com/objectbox/objectbox-dart/issues/342#issuecomment-1897957433_

**Comment by greenrobot-team** [comment]
Answered in associated issue, closing as a duplicate of #342.
