### ISSUE TITLE
ObjectWithScore class not exported

### ISSUE THREAD

**Issue by davidmigloz** [objectbox/objectbox-dart#637]
### Is there an existing issue?

- [x] I have searched [existing issues](https://github.com/objectbox/objectbox-dart/issues)

### Build info

- objectbox version: 4.0.0
- Dart version: 3.4.0

### Steps to reproduce

The `ObjectWithScore` class doesn't seem to be exported in `package:objectbox/objectbox.dart`.

### Expected behavior

The class should be exported from the public library.

### Actual behavior

Currently, you can only access `ObjectWithScore` if you import the private library:
```dart
import 'package:objectbox/src/native/query/vector_search_results.dart' show ObjectWithScore;
```

**Comment by greenrobot-team** [comment]
Thank you so much! Totally missed this because I postponed writing the example project.

A fix is available internally (`objectbox/objectbox-dart!85`), will ship with the next release.

**Comment by greenrobot-team** [comment]
Release `4.0.1` is available which fixes this issue.

To update to this release, for a Flutter project run `flutter pub upgrade` or for a Dart Native project `dart pub upgrade`.

**Comment by davidmigloz** [comment]
Awesome, thanks for the quick fix.

I'll update it at https://github.com/davidmigloz/langchain_dart/pull/438 (we plan to release it this week)
