### ISSUE TITLE
objectbox-generator: outdated cryptography dependency

### ISSUE THREAD

**Issue by feykro** [objectbox/objectbox-dart#643]
### Is there an existing issue?

- [x] I have searched [existing issues](https://github.com/objectbox/objectbox-dart/issues)

### Use case

The current cryptography package dependency is `2.0.5` while the current version of the package is `2.7.0`. This has caused me a problem when trying to use both objectBox and flutter_sound, as flutter_sound is up-to-date on the latest version of js while the old `2.0.5` version of cryptography depends on an older version of js, namely `0.6.2`. This causes incompatibilities.

### Proposed solution

Upgrade dependency of cryptography to the latest version

### Describe alternatives you've considered

I have tried to fork and do it myself but I've ran into issues I have 0 experience with.

**Comment by greenrobot-team** [comment]
Despite checking the box about searching existing issues, I guess you did not find #638.

Closing as duplicate.
