### ISSUE TITLE
ToMany adds sort memory

### ISSUE THREAD

**Issue by JunhuaAhuaChen** [objectbox/objectbox-dart#644]
Each time the ToMany property is accessed, a list sorted by id is returned, and the order cannot be changed

**Comment by greenrobot-team** [comment]
These are the target objects of that `ToMany`. [See the docs](https://pub.dev/documentation/objectbox/latest/objectbox/ToMany-class.html).

Or is this about being able to define the order of the target objects (like [requested for the Java library](https://github.com/objectbox/objectbox-java/issues/154))?

**Comment by JunhuaAhuaChen** [comment]
Yeah, that's it.
https://github.com/objectbox/objectbox-java/issues/243#issuecomment-341355922
I prefer the first one because when the relationship changes, the sort properties may not be known and need to be manually updated.
For example, 1to2, 2to3, is using 3, delete 2 by 3.2.
