### ISSUE TITLE
Cannot figure out default value for field: Salescategory salesCategory

### ISSUE THREAD

**Issue by yashanghan22** [objectbox/objectbox-dart#647]
**cannot generating g dart file using objectbox package just because of my class has one custom type enum parameter which is causing a issue don't know it is issue or not so want to know is there any solution for this ?????**

### Build info

- objectbox version: 4.0.1
- Flutter/Dart version: 3.19.6/3.2.6
- Build OS:  Windows 10
- Deployment OS or device: windows

### Expected behavior

it should generate g dart file if i put any enum parameter in the class

### Actual behavior
it is not generating dart file and throwing error as shown below in th screenshot
![image](https://github.com/objectbox/objectbox-dart/assets/53462202/063b5218-7b1c-427e-ae4e-2b1741c8df11)

### Code

<details><summary>Code</summary>

```dart
@Entity()
class SalesConverterModel {
  @Id()
  int? id;
  @Property()
  Salescategory salesCategory;
  PartyModel? partyName;
  String? broker;
  String? onAc;
  String? outstate;
  String? qaulity;

  SalesConverterModel({
    this.id,
    this.salesCategory = Salescategory.sales,
    this.partyName,
    this.broker,
    this.onAc,
    this.outstate,
    this.qaulity,
  });
}
```

</details>

**Comment by greenrobot-team** [comment]
ObjectBox can not know how to convert `SalesCategory` to a database value, even if you add the `@Property` annotation. It needs to be mapped to a supported type, like an `int` or `String`. See https://docs.objectbox.io/advanced/custom-types#convert-annotation-and-property-converter for an example.

Note: this issue will auto-close in a few days if there are no follow-up comments.

**Comment by yashanghan22** [comment]
@greenrobot-teamI, I understand that I need to assign values to each enum property, correct?

**Comment by greenrobot-team** [comment]
You need to add methods to convert to a database value, like shown at https://docs.objectbox.io/advanced/custom-types#convert-annotation-and-property-converter

**Comment by yashanghan22** [comment]
@greenrobot-team, got it. Thanks for the solution.
