### ISSUE TITLE
Admin: on macOS no database found at location

### ISSUE THREAD

**Issue by Aruljebaraj** [objectbox/objectbox-dart#651]
Objectbox Admin (Docker-Version)

NOTE: No database found at location '.', trying default location ('./objectbox') ..
 in MacOs

**Comment by greenrobot-team** [comment]
Can you share which command you have used to run the Admin Docker image? Our recommended script requires that the data.mdb file is in a directory called objectbox next to it.

**Comment by Aruljebaraj** [comment]
tried this even made permission changes and copied to specified directory usr/local/ still got No database found at location '.', trying default location ('./objectbox') ..

**Comment by greenrobot-team** [comment]
Just tried this on macOS 13.6 and the `objectbox-admin.sh` can find a database file:
```
Objectbox Admin (Docker-Version)

Found database at local location '/Users/objectbox/Downloads'.
Open http://127.0.0.1:8081 in a browser.
Once done, hit CTRL+C to stop 'ObjectBox Admin' Docker container.
==================================================================
```

These are the permissions:
```
-rw-r--r--   1 objectbox  staff    32K Feb 13 10:30 data.mdb
-rwxr-xr-x@  1 objectbox  staff   1.6K Jul 15 10:37 objectbox-admin.sh
```

Maybe this is a macOS permissions issue? But on my test machine only Terminal has access to the Downloads folder I used.
