### ISSUE TITLE
Put String as table name and Map(JSON) as data. (A Db access function that don't use Entity)

### ISSUE THREAD

**Issue by normidar** [objectbox/objectbox-dart#659]
### Is there an existing issue?

- [x] I have searched [existing issues](https://github.com/objectbox/objectbox-dart/issues)

### Use case

I am using another database and plan to use ObjectBox.

I have a wrapper to access all my databases, so I can't create an `@Entity` annotation for ObjectBox on my application.

### Proposed solution

A way to put, get, etc (curd) by `Map<String, Object?>` type.

### Describe alternatives you've considered

Have not.

### Additional context

[empty]

**Comment by normidar** [comment]
I haven't used ObjectBox before, but I'm looking for a way to store data like this: `.put({'name': 'abc', 'age': 19})`

**Comment by greenrobot-team** [comment]
> I haven't used ObjectBox before, but I'm looking for a way to store data like this: `.put({'name': 'abc', 'age': 19})`

This is not possible, as I said the whole point of ObjectBox is that it works with Dart classes. With that said, it is possible to create an `@Entity` class that just contains a `String` property:

```dart
@Entity()
class Wrapper {
  @Id()
  int id;
  String value; // Store the JSON here

  Wrapper({this.id = 0, required this.value});
}
```

But then there are no benefits like queries or indexes.

**Comment by normidar** [comment]
Okay, thanks.
I will close the issue.
