### ISSUE TITLE
Avoid copying >1

### ISSUE THREAD

**Issue by Buggaboo** [objectbox/objectbox-dart#69]
```dart
    // TODO (perf) find a way to get access to the underlying memory of Uint8List to avoid a copy
    //  In that case, don't forget to change the caller (FlatbuffersManager) which expect to get a copy
    // if (data.length == bytes.length) {
    //   bytes._dataPtr = data.some-way-to-get-the-underlying-memory-pointer
    //   return ptr;
    // }
```

I saw [this bit of code](https://github.com/objectbox/objectbox-dart/blob/dev/lib/src/bindings/structs.dart#L74L79) and did some research, then came to the conclusion, that dart doesn't have a `List` to `UnsafePointer` type (yet).

To avoid copying twice (i.e. once for collecting bytes in the buffer, to flatten the entity, twice for copying the buffer to the `Pointer` alloc), you might as well not use the (flat buffer) builder, and directly allocate a `Pointer<Uint8>`(?) with the the proper payload. The new builder should allocate, align and copy at the last moment, when `finish` is called. 

I'm not completely sure if the changes should be made on google's builder, or this project's.

**Comment by vaind** [comment]
This [ffi issue](https://github.com/dart-lang/ffi/issues/27) addresses the same problem and I don't think there is going to be a solution, considering Uint8List backing memory may be moved around. I'll update the comment and reference that issue.
