### ISSUE TITLE
Issue  while using isolates 

### ISSUE THREAD

**Issue by Aruljebaraj** [objectbox/objectbox-dart#696]
I’ve implemented a singleton pattern for the ObjectBox class in my Flutter project, and it works correctly when accessed normally. However, when I started implementing isolates, I'm encountering a LateInitializationError.

```dart
import 'package:inspectassist_bloc/objectbox.g.dart';

class ObjectBox {
  late final Store store;
  late final Box<Test> testBox;

  ObjectBox._create(this.store) {
    testBox = Box<Test>(store);
  }

  static late final ObjectBox _instance;

  static Future<void> init() async {
    _instance = ObjectBox._create(await openStore());
  }

  static ObjectBox get instance => _instance;
}
```

```
LateInitializationError: Field '_instance@85511379' has not been initialized.
#0      ObjectBox._instance (package:inspectassist_bloc/Database/ObjectBox.dart)
#1      ObjectBox.instance (package:inspectassist_bloc/Database/ObjectBox.dart:59:36)
```

is there any solution to fix this

**Comment by Aruljebaraj** [comment]
- tried to initialise it again 
-  BackgroundIsolateBinaryMessenger.ensureInitialized(rootIsolateToken);   // rootToken -- null

**Comment by Aruljebaraj** [comment]
can I get an example ?

**Comment by greenrobot-team** [comment]
Sorry, I can't really help without an error message or code example. But this error message does not sound like it is related to ObjectBox.

Note: I labeled this issue with "more info required" so it will auto-close in a few days if there are no follow-up comments.

**Comment by Aruljebaraj** [comment]
The BackgroundIsolateBinaryMessenger.instance value is invalid until BackgroundIsolateBinaryMessenger.ensureInitialized is executed.

**Comment by greenrobot-team** [comment]
I added notes about this to the Getting Started - [Create a Store sections](https://docs.objectbox.io/getting-started#create-a-store) for Flutter and Dart.
