### ISSUE TITLE
Support array types

### ISSUE THREAD

**Issue by vaind** [objectbox/objectbox-dart#84]
ObjectBox C provides native support for arrays of strings and bytes - mainly to execute queries on those. We should support them in Dart as well. 

The following types should be supported:
* List<String>
* Uint8List and/or ByteData?

**Comment by lzhAndroid** [comment]
is it support now?

**Comment by vaind** [comment]
No, it's not implemented in the dart binding yet. Any help would be appreciated if you'd like to pick this issue up and give implementation a go yourself.

**Comment by vaind** [comment]
For ByteVector, we should support:
* `Uint8List` [File::readAsBytes()](https://api.dart.dev/stable/2.10.4/dart-io/File/readAsBytes.html)
* `Int8List` (maybe, should be trivial with the other in place so why not?)
* `List<int>` [BytesBuilder::add()](https://api.dart.dev/stable/2.10.4/dart-typed_data/BytesBuilder/add.html) [ZlibDecoder::convert()](https://api.dart.dev/stable/2.10.4/dart-io/ZLibDecoder/convert.html)

**Comment by vaind** [comment]
implemented by #156
