### ISSUE TITLE
Android release build failure

### ISSUE THREAD

**Issue by vaind** [objectbox/objectbox-dart#87]
`flutter build appbundle` and `flutter build ios` currently fail for the example. I'll later add more details, trying to pinpoint the issue. 

```
Running "flutter pub get" in objectbox_demo...                      0.5s
                                                                        
===== CRASH =====                                                       
si_signo=Segmentation fault(11), si_code=1, si_addr=0x48                
Dart snapshot generator failed with exit code -6                        
Target android_aot_release_android-arm failed: Exception: AOT snapshotter exited with code -6
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '~/lib/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '~/lib/flutter/bin/flutter'' finished with non-zero exit value 1                                                                    
```

**Comment by vaind** [comment]
Maybe related: https://github.com/flutter/flutter/issues/47060

**Comment by vaind** [comment]
Created a flutter issue: https://github.com/flutter/flutter/issues/47454

**Comment by contactlockten** [comment]
My code does not have elementAt. I created fresh new project and without adding my code at all i tired.
-------------------------------------------------------------------------------------
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (2 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
----------------------------------------------------------

Error 👍 Dart snapshot generator failed with exit code -9                        
Target android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code -9
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/athorat/mobile/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/Users/athorat/mobile/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 6s                                                      
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                         7.4s
Gradle task bundleRelease failed with exit code 1
