### ISSUE TITLE
Exception: Failed To Create Store

### ISSUE THREAD

**Issue by ibcoleman** [objectbox/objectbox-dart#99]
With ObjectBox 0.6.2 on 

```
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.4 19E266, locale en-US)
    • Flutter version 1.15.17 at /Users/ian/Applications/flutter
    • Framework revision 2294d75bfa (4 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)
```

I get the following error when I try to call put() on an android device. Is there something in the manifest I need to add?

```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following ObjectBoxException was thrown while handling a gesture:
failed to create store: 10199 Dir does not exist: objectbox (30)

When the exception was thrown, this was the stack: 
#0      checkObxPtr (package:objectbox/src/bindings/helpers.dart:15:5)
#1      new Store (package:objectbox/src/store.dart:43:5)
#2      _MyAppState.barcodeBox (package:flutterbarcodes/home.dart:27:46)
#3      _MyAppState.barcodeBox (package:flutterbarcodes/home.dart:27:14)
#4      _MyAppState._handleSaveButton (package:flutterbarcodes/home.dart:192:14)
```

**Comment by qiushouchen** [comment]
> 启用ObjectBox 0.6.2
> 
> ```
> [✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.4 19E266, locale en-US)
>     • Flutter version 1.15.17 at /Users/ian/Applications/flutter
>     • Framework revision 2294d75bfa (4 weeks ago), 2020-03-07 00:28:38 +0900
>     • Engine revision 5aff311948
>     • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)
> ```
> 
> 当我尝试在android设备上调用put（）时收到以下错误。清单中是否需要添加一些内容？
> 
> ```
> ════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
> The following ObjectBoxException was thrown while handling a gesture:
> failed to create store: 10199 Dir does not exist: objectbox (30)
> 
> When the exception was thrown, this was the stack: 
> #0      checkObxPtr (package:objectbox/src/bindings/helpers.dart:15:5)
> #1      new Store (package:objectbox/src/store.dart:43:5)
> #2      _MyAppState.barcodeBox (package:flutterbarcodes/home.dart:27:46)
> #3      _MyAppState.barcodeBox (package:flutterbarcodes/home.dart:27:14)
> #4      _MyAppState._handleSaveButton (package:flutterbarcodes/home.dart:192:14)
> ```

You should clarify the store directory like the [example project](https://github.com/objectbox/objectbox-dart/blob/master/example/flutter/objectbox_demo/lib/main.dart#L70)

**Comment by ibcoleman** [comment]
Thanks! That was exactly it. Also added the path_provider dependency. Thanks Jochen!
